### ISSUE TITLE
Add visibility annotation to JohnTravoltageView peerId's

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#103]
Related to #98, this sim uses 

```js
this.peerIDs = {
      alert: 'john-travoltage-alert',
      status: 'john-travoltage-status'
    };
```
to reference the ```aria-live``` elements in the of the top level html file.

Would you mind adding  a ```@public```, ```@private```, or ```@protected``` annotation above this.peerID's to describe if these are meant to be used outside of the ScreenView?

**Comment by jobara** [comment]
@jessegreenberg rather than adding an annotation to the code, I moved the peerIDs from being attached to `this` to being part of the `options`. In this way, they can be overridden at instantiation time.

**Comment by jessegreenberg** [comment]
@jobara that looks good - thanks for the informative TODO comment and reference to #98.  Closing
