### ISSUE TITLE
Style of alertNode in SparkNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#104]
In SparkNode, alertNode is styled by

```js
        if (alertNode && !alertNode.textContent) {
          alertNode.textContent = dischargeAlertText;
          alertNode.style.display = 'block';
        }
```

Does the alert node need to be styled or can that line be removed?  If it does need to be styled, please add documentation explaining why.

Also, I would recommend that alertNode be renamed to alertElement.  alertNode points to a PDOM element and if it is called alertNode it looks like a scenery.Node.

**Comment by jessegreenberg** [comment]
Thanks @jobara, that is really interesting.  So is ```style.display = 'none';``` equivalent to ```aria-hidden``` and ```hidden```?  Does the style hide it from the virtual cursor?

Reassigning to @jobara for further discussion.

**Comment by jessegreenberg** [comment]
My question is now unrelated to code review, removing tag.

**Comment by jobara** [comment]
@jessegreenberg `display: none` removes the content from the accessibility tree as well as visually. It also removes it from the content flow. `visibility: hidden` removes it from the accessibility tree and visually, but it's affect on the content flow still remains. `aria-hidden` removes it from the accessibility tree only. This article does a good job of explaining the various ways of hiding elements ( http://terrillthompson.com/tests/hiddencontent.html ), it also captures that issue we had with the 0 height.

In this particular case we could probably just use aria-hidden. Would you like me to switch to this?

**Comment by jessegreenberg** [comment]
I see, that's interesting, thanks for explaining @jobara.  And thanks for the article!  Interesting to see the 0 height issue here.

aria-hidden or hidden seems more intuitive to me, but now that I understand how style display works, I don't have a strong preference.  If you keep style.display would you mind adding a comment to the code sort of like what you have above?
>display: none removes the content from the accessibility tree as well as visually. It also removes it from the content flow.

**Comment by jobara** [comment]
@jessegreenberg I switched to using `aria-hidden="true"`, and have updated my branch.

**Comment by jessegreenberg** [comment]
Thanks @jobara!  Closing this issue.  https://github.com/phetsims/john-travoltage/issues/104#issuecomment-228324141 was very informative!
