### ISSUE TITLE
Merge accessible content into master

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#106]
We are ready to add prototype accessibility code into master.   This issue is to make sure those working in john-travoltage are aware that this is about to happen.  @jbphet is especially working on this sim for sonification, so I will merge once I coordinate with him so things don't get too confusing.

**Comment by jessegreenberg** [comment]
@jobara, the merge is complete!  Closing this issue.

**Comment by jobara** [comment]
@jessegreenberg that's great, thanks.
