### ISSUE TITLE
Electrons quantity live region not being reported in Dev 5

### ISSUE THREAD

**Issue by jhung** [phetsims/john-travoltage#111]
With Dev 5 version of John Travoltage, the quantity of electrons live region does not get reported.

To reproduce

1. load:
http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-dev.5/john-travoltage_en.html?accessibility
2. turn on a screen reader
3. Using the keyboard move the foot slider
4. Accumulate a few charges
5. Notice that the number of charges do not get reported

I took a look at the DOM and I couldn't find the live region for the electrons.

**Comment by jessegreenberg** [comment]
Sorry about that @jhung, I see the issue.  Deploying a new version now.

**Comment by jessegreenberg** [comment]
@jhung here is a redeployed version, live elements are in the document and I hear the alerts with NVDA and Chrome and Firefox.

http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-dev.5/john-travoltage_en.html?accessibility

**Comment by jhung** [comment]
I tested also with VoiceOver with FF and Safari on Mac. Looks good. Thanks!
