### ISSUE TITLE
HTML in danger of being overwritten

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#112]
I noticed that john-travoltage_en.html has the following added html:

```html
<p id="john-travoltage-alert" role="alert"></p>
<p id="john-travoltage-status" role="status" aria-live="polite" aria-atomic="true"></p>
```

This would be eliminated if someone ran the `grunt generate-development-html` task.  Perhaps it would be safer to (a) generate those dom elements programmatically from JS or (b) change the development-html template to include that for every sim if it is ready for production.

**Comment by jessegreenberg** [comment]
Agreed, these too easily removed at the moment.  In the long run, we would like this content to be in the top level html file for every sim, but I am not sure yet what kind of specific attributes for aria-live we need to support (aria-relevent, atomic level, specific role, etc...) or if the content needs some structure.  We have some discussion on this here https://github.com/phetsims/chipper/issues/472.

It would be ideal to generate these elements programatically with JS!  Unfortunately, screen readers don't observe 'aria-live' elements that are added dynamcially, they are only able to listen for changes to elements that exist on the page on load.

**Comment by samreid** [comment]
> Unfortunately, screen readers don't observe 'aria-live' elements that are added dynamcially, they are only able to listen for changes to elements that exist on the page on load.

That is interesting, I wouldn't have guessed that.

In that case, could these divs be given more general names?  They are currently:

```html
<p id="john-travoltage-alert" role="alert"></p>
<p id="john-travoltage-status" role="status" aria-live="polite" aria-atomic="true"></p>
```

What if it was something that could be used for every simulation:

```html
<p id="phet-accessibility-alert" role="alert"></p>
<p id="phet-accessibility-status" role="status" aria-live="polite" aria-atomic="true"></p>
```

Do these elements have appropriate CSS so it won't disrupt any of the other dom elements?  If so, we could work on moving this into the general template.

**Comment by jessegreenberg** [comment]
These elements have been moved to the dev and sim templates, closing.
