### ISSUE TITLE
Replace _.sample with phet.joist.random.sample

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#115]
From https://github.com/phetsims/phet-io/issues/551#issuecomment-240894295

@pixelzoom recommended:

> Looks like `_.sample` is used only in john-travoltage.  Recommended to replace it immediately, so there's one less thing to search for during conversion.

It's an easy change to make, but I'm not certain how to to test this, so I'll leave this up to @jbphet.

**Comment by jbphet** [comment]
I've replaced _.sample with phet.joist.random.sample.  In this case, the result will be that the sonfication behaves consistently when played back.  Hadn't really thought about it, but that's probably a good thing.  Closing.
