### ISSUE TITLE
parseInt missing radix argument

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#116]
`JohnTravoltageQueryParameters` contains 1 call to `parseInt` with no radix argument. 

[Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) for `parseInt` says:

>  Different implementations produce different results when a radix is not specified, usually defaulting the value to 10.

**Comment by pixelzoom** [comment]
Fixed, but I'm not clear on how to test this (related to signification). Assigned to @jbphet to verify.

**Comment by jessegreenberg** [comment]
Now that john-travoltage is using QueryStringMachine this is no longer relevant.  Closing.
