### ISSUE TITLE
Mute button needs aria-pressed to define state

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#119]

**Comment by jessegreenberg** [comment]
Doing this in sim directly to avoid churn in master for the moment.

**Comment by jessegreenberg** [comment]
Note to self:  A button element inside of a form will automatically submit the form.

**Comment by jessegreenberg** [comment]
Done in the commit above, NVDA says 'Play Sound toggle button, not pressed' or Play Sound toggle button, pressed'.

**Comment by jobara** [comment]
@jessegreenberg from reading the description you mentioned, I'm not actually sure what to expect. Does it play the sound when pressed or not? My initial inclination is to think it needs to be pressed for the sound to play, but that seems unconventional compared to other systems where you'd play sound by default and activate mute.

> NVDA says 'Play Sound toggle button, not pressed' or Play Sound toggle button, pressed'.

**Comment by jessegreenberg** [comment]
Thanks @jobara, my thought was that "play sound" toggle button would play the sound when pressed, and it is pressed by default.

Would you recommend "Mute Sound toggle button" instead, not pressed by default?

**Comment by jhung** [comment]
@jessegreenberg I that makes more sense... have a "Mute sound toggle" unchecked by default.

**Comment by jessegreenberg** [comment]
Thanks @jhung, The above commit changes to the behavior to "Mute Sound toggle button, not pressed" by default and "Mute Sound toggle button, pressed" when the button is in its pressed state.

Closing.
