### ISSUE TITLE
Replace getQueryParameter with QueryStringMachine

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#124]
Factored out of https://github.com/phetsims/query-string-machine/issues/15

**Comment by pixelzoom** [comment]
I started to convert this, but discovered that the type of `sonification` query parameter is `{boolean|number}`.   This is not supported by QueryStringMachine.  @jbphet you'll have to handle this.  Highly recommended to use `{type 'number'}`, with a default value that does what you want when this is currently false.

**Comment by pixelzoom** [comment]
Looks like @jessegreenberg self assigned, so I won't assign to @jbphet.

**Comment by jessegreenberg** [comment]
Done in the commit above.  I checked with @jbphet and also a default value as described in https://github.com/phetsims/john-travoltage/issues/124#issuecomment-257431731.  I added documentation for each value based on http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-dev.3/jt-sonification-1-3-0-dev-2-release-notes.html.

Closing.
