### ISSUE TITLE
Design of Popup Dialogue for Keyboard Nav Help

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#127]
We need to design the dialogue popup that will inform users of the keyboard presses available for using the sim. 

Here's the list of keyboard presses and actions (from Jon H.):

- Right Arrow and Up Arrow: Increase the value of the slider.
- Left Arrow and Down Arrow: Decrease the value of the slider.
- Home and End: Set the slider to the first and last values of the slider.
- Tab: Moves focus into and out of the slider.
- Page Up and Page Down (Optional): Increment or decrement the slider by an amount larger than the step changes made by the arrow keys.

There also will probably be a shortcut key to bring up this "help" info.

@arouinfar - can you mockup a popup box, similar to @terracoda 's mockups for BASE? (Ideally before the Thanksiving break). Note: all the key presses in JT are "standard", unlike in BASE, so JT's popup will be much simpler.

<img width="566" alt="screen shot 2016-11-18 at 9 20 37 am" src="https://cloud.githubusercontent.com/assets/5109055/20437221/58d154b2-ad70-11e6-900c-58d48e1bc543.png">

**Comment by terracoda** [comment]
@arouinfar, I'm sure you can make it look better than my original mock-up :-)

**Comment by arouinfar** [comment]
@emily-phet I can work on this later this afternoon (depending on how long it takes to get through the Google Drive migration) or Monday.

@terracoda your mockup is a really helpful place to start. :)

**Comment by arouinfar** [comment]
@emily-phet I've made a few (wireframe) iterations of the keyboard popup, which you can view in
[Keyboard_Shortcut.pdf](https://github.com/phetsims/tasks/files/625424/Keyboard_Shortcut.pdf). I've included some comments to the .pdf file.

I prefer the last mockup in the file (pasted below). It groups the keys into categories, which I think will be a useful paradigm for other sims, as @terracoda's initial mockups have indicated.
<img width="779" alt="screen shot 2016-12-01 at 11 05 33 am" src="https://cloud.githubusercontent.com/assets/8419308/20805948/1f412c68-b7b6-11e6-9d23-0cc17d9200e7.png">

@emily-phet please let me know your thoughts. I can polish up the mockups a bit more once I get some general layout/content feedback.

**Comment by jobara** [comment]
@arouinfar one of the tricky things with the JT sim is the circular motion of the appendages. Basically the ↑doesn't always move the hand/foot up visually. Consider the case where the leg is all the way back, pushing ↑ will actually make the foot look like it's going down.

**Comment by arouinfar** [comment]
> pushing ↑ will actually make the foot look like it's going down

Excellent point @jobara. I struggled a bit with how to describe the motion because the hand and foot sometimes seem discrepant. 

I'm hesitant to describe anything as a "slider" (even though it simplifies the text to some extent) because it seems like a nitty-gritty implementation detail that doesn't need to be revealed to the user. @jessegreenberg has pointed out that the screen reader refers to the hand/foot as a slider, but not everyone using keyboard navigation would also be using a screen reader. 

I'm also wondering about the choice of home/end and page up/page down. These are Windows-specific keys. Within the sim, the Mac equivalents would be
* fn + up = page up
* fn + down = page down
* fn + left = home
* fn + right = end

Will Mac users be able to translate the keys themselves, or do we need to have a separate Mac help menu popup? I'm not overly confident about the former, because cmd+arrows can at times act like fn+arrows, depending on the context/application.

**Comment by arouinfar** [comment]
What I've been calling up/down works nicely for the hand, but the foot is different as @jobara has pointed out. Here an alternative:

<img width="772" alt="screen shot 2016-12-01 at 12 00 03 pm" src="https://cloud.githubusercontent.com/assets/8419308/20807865/c50c648a-b7bd-11e6-94db-a78965dcf283.png">

**Comment by jhung** [comment]
@arouinfar and @emily-phet, I made [a quick sketch](https://docs.google.com/drawings/d/1gCaKzMMq7KqPYqqeQ9Uvrv3Lv22iVfEMsM5e_BjtSoQ/edit?usp=sharing). Because of the issue @jobara mentioned I think we can avoid the confusion by simplifying and grouping the text (see the sketch).

I think it's okay to not be too specific in wording - we've observed that users are quick to figure out which direction they want to go after the initial key press (even if the key press moves the arm/leg in a direction they weren't expecting).

The way I see it, the home/end and pgup / pgdn keys aren't really important. They're convenient if you need them, but most cases users will be using up/down or left/right.

**Comment by jobara** [comment]
@arouinfar and @jhung, the home/end and pgUp/Dn keys are not critical. They are features we just get for free with the slider. 

@arouinfar you make an interesting point about key name. I suppose it's keyboard dependent as I still use an Apple keyboard that has home/end and pageUp/Dn keys, although this is becoming more and more uncommon. I wonder if there are PC laptops with similar key combination requirements too. However, the user may know or easily discover how to do those actions.

**Comment by arouinfar** [comment]
@jhung thanks for the sketch! It's really helpful.

@jobara I'll mock up a few more alternatives based on @jhung's sketch, both with and without the home/end and page up/down keys. I compared keyboards with a coworker who uses a small Dell laptop, and she also needs to use the fn + arrow keys. However, her arrow keys look something like this:

<img width="286" alt="screen shot 2016-12-01 at 5 19 40 pm" src="https://cloud.githubusercontent.com/assets/8419308/20818373/625c8144-b7ea-11e6-909d-f4ad9d568609.png">

**Comment by terracoda** [comment]
@arouinfar, @jhung, @jobara, I also think Jon's approach is a nice one. I suggest the wording name the actual  keys in the description, so it is clear for both visual and non-visual users. The actual images can then have blank alt text in the underlying HTML making them invisible to a screen reader user, thus making the reading experience more pleasant.

For example:
**Left and right arrows keys** move the foot and hand a small amount. 
**Tab ke**y moves to next item.
**Shift plus Tab** moves to previous item.

Could add "in opposite directions" for the arrow keys if you think that is helpful, but that should be obvious (implicit and intuitive) with arrow keys.

Also as @jhung mentioned, no need for "closer to door" as the foot rubs forward and back on the rug and the hand moves more explicitly towards the metal doorknob.

Also, I don't think the word "focus" is necessary. The student has to have focus on the control to operate it.

**Comment by arouinfar** [comment]
Thanks for these suggestions @terracoda.

> Could add "in opposite directions" for the arrow keys if you think that is helpful, but that should be obvious (implicit and intuitive) with arrow keys.

I agree that this should be obvious, though it could quickly be observed by visual users. However, would it be helpful to non-visual users to add "in opposite directions"?

Here are a few mockups that combine @jhung's sketch with @terracoda's text suggestions. The first is a more verbose, and the second more minimal. I could make an argument for either.
![screen shot 2016-12-02 at 12 44 58 pm](https://cloud.githubusercontent.com/assets/8419308/20847899/2dea7b52-b88d-11e6-87e6-033896521db7.png)

![screen shot 2016-12-02 at 12 43 46 pm](https://cloud.githubusercontent.com/assets/8419308/20847859/021b9510-b88d-11e6-80a7-35b0f93c5089.png)

I'm also wondering if it's necessary to include instructions for the Tab and Shift+Tab commands. Aren't these standard in keyboard navigation?

**Comment by terracoda** [comment]
@arouinfar, yes Tab and Shift Tab very common keyboard operations. They would likely only not work if the app was not built correctly from the start. However, that said, this is an interactive sim, not a typically accessible application. Providing some instructions that standard key presses work may provide assurance to some users. In my interviews, participants did think aloud phrases like this:
> Will pressing the Escape key close the dialog?

And then they proceeded to press the Escape key and it worked as they had wondered out loud.

I think it is ok to add some key explicit things. They can choose not to read it, especially when the document is well organized and easily navigable. Some sims will have more complicated help than others. 

An example from my early research on this was from a flickr app, their help dialog included a statement like, 
> Escape key closes dialogs, like this one.

Which could be nice at the very end, also under the "General operations" heading.

Regarding the title - just noticed that - I prefer "Hot keys and Help". One participant I interviewed early on where the cue just said "Press H key for Help" commented something like

> I don't need help. I just need to know how it works.

I notice your ??? question marks. We are using the "H key" for "Hot keys and Help" in BASE for a few reasons:

- We don't have an accessible button to use.
- We can only use a key while in Application mode because screen reader hot keys use everything else.
- The H key does not require the shift key.

Once there is a visual button in the sim header/footer, a Hot Key for help may not be necessary.

**Comment by arouinfar** [comment]
Thanks for the feedback @terracoda! I was using ??? as a placeholder, because @emily-phet's original post didn't specify the key.

> I think it is ok to add some key explicit things. They can choose not to read it, especially when the document is well organized and easily navigable. Some sims will have more complicated help than others.

Sounds good. I think for a sim like BASE, we'll want to have some top-level categories for sim-specific things, and more general navigation. If we go the more minimal route, I think everything can be listed together, like so:

![screen shot 2016-12-02 at 2 10 19 pm](https://cloud.githubusercontent.com/assets/8419308/20850615/4bc28834-b899-11e6-9332-aeb78297fe9e.png)

**Comment by terracoda** [comment]
@arouinfar looking good. Just a couple of  adjustments.

I would put periods at the end of each, so there are pauses at the end. 

I should have said "**Escape key** closes a dialog, like this one."

And, to be consistent, I would refer to "this page" with the same language, so:

"**H key** opens this dialog." It's a dialog not a menu :-)

**Comment by arouinfar** [comment]
How about this @terracoda? If the verbiage and ordering looks good, I can start working on aesthetics. 
![screen shot 2016-12-05 at 12 25 15 pm](https://cloud.githubusercontent.com/assets/8419308/20899028/e93ccd06-bae5-11e6-9990-0931e1a6b4f8.png)

**Comment by terracoda** [comment]
@arouinfar, 

> Shift plus Tab keys move to next item.

 sounds a bit awkward. Sorry I didn't catch that before. I think,

> Shift plus Tab moves to previous item.

sounds better.
Other than that, it's great!

**Comment by arouinfar** [comment]
Thanks @terracoda! I will start working on a few layout options

**Comment by emily-phet** [comment]
Looking great! @arouinfar I would suggest returning to earlier wording for the description of the arrow keys - "Left and Right arrow keys move the hand or the foot". I think "opposite directions" could be confusing. 
I'm not sure about the use of "dialog". It's true that it is a dialog, but I doubt many people really know what that means - so likely it will just be ignored. Let's go with the use of "dialog" but keep an eye out for feedback that this is confusing to users. The addition of "like this one" helps.  @terracoda's interviews were with people quite adept (in general) with their screen readers, which announce what type of element they're interacting with. Most users aren't exposed to that level of detail in their typical web interactions.

**Comment by arouinfar** [comment]
Thanks for the feedback @emily-phet! I will make the suggested changes to the descriptions, and work on a few mockups later this afternoon.

**Comment by terracoda** [comment]
@emily-phet, @arouinfar other possible words for "dialog" could be:

- modal (also a bit technical)
- pop-up
- pop-up box
- window
- pop-up window
- document (a bit dry)

Just words to keep in the coffers. And the addition of "like this one," would be god in all cases.

**Comment by arouinfar** [comment]
Thanks for these suggestions @terracoda. I think "pop-up" might be a good alternative to "dialog".  I also like window, but I think it could get confused with the browser window.

The good news is that once the dialog is implemented, it'll be really easy to make changes to the text. :)

**Comment by jobara** [comment]
@terracoda and @arouinfar, I hadn't thought of this till your naming discussion above, but is the "pop-up" actually going to be modal?

**Comment by arouinfar** [comment]
@jobara the help dialog will modal (like the About menu). We don't yet have support for non-modal dialogs.

**Comment by terracoda** [comment]
@jobara, currently these "pop-ups" are implemented in Scenery as a "modal dialog" as opposed to a either a "non-modal dialog" or an "alert dialog".

As currently, implemented in BASE the modal content is accessible. With the aria document role applied to the modal users are able to navigate the content just as they navigate a typical web page with content.

We have had some issues with a user slipping back into the sim content without exiting the modal which is a bug,

**Comment by terracoda** [comment]
@arouinfar, FYI, we are investigating alternative options to using a modal dialog for the actual pop-up of the list of items.

**Comment by emily-phet** [comment]
@terracoda - you might want to respond elsewhere, if this is getting off-topic, but why would we want a non-modal dialog? I was thinking that modal dialogs were more intuitive (they open and you have to close them to get back to where you were) and that this might help create that barrier between interacting with the dialog and interacting with what's behind the dialog. I'm just curious, because I feel like perhaps I have misunderstood something in a prior conversation. Note: I'm imagining that all the modal dialogs we're considering in the accessibility work would have an "x" to close button, so it would be more clear that this is modal and you need to do something to "return" to the sim.

**Comment by terracoda** [comment]
@emily-phet, I'm not suggesting we not use modal dialogs for actual pages that pop-up (the resources that are available from the menu). What @jessegreenberg and I would like to see is if we can make the actual menu pop-up be just a menu that pops up rather than popping up in a modal dialog.

For example, a collapsed (hidden) menu, might be easy to use than a modal. This should make the structure simpler and eliminates the need for a close button.

**Comment by emily-phet** [comment]
Thanks for the clarification - that makes sense.

**Comment by arouinfar** [comment]
I've made a few small adjustments to the text based on @terracoda and @emily-phet's suggestions, and have added the dialog close button. I left the references to "dialog" for now, but we can find a suitable alternative during user testing (if necessary).

I think we're ready to do a bit of pixel-polishing to the dialog's appearance. The all black and white version felt a bit boring to me, so I added a little color. I used a less-saturated version of PhET blue as a stand-in, which passes WCAG contrast standards against black. (Fully saturated PhET blue also passes, but I found it to be a bit too bright.) 

@emily-phet and @terracoda do either of you have any thoughts in mind for how this dialog might appear? I imagine we'll keep it relatively simple, which is why I tried colored keys or a colored background. Personally, I prefer the former. I'm also available to schedule a Zoom chat later this week, if you think it'd be more efficient.

![screen shot 2016-12-12 at 2 08 22 pm](https://cloud.githubusercontent.com/assets/8419308/21116853/8246822e-c074-11e6-9741-0db084b77c12.png)
![screen shot 2016-12-12 at 2 08 30 pm](https://cloud.githubusercontent.com/assets/8419308/21116852/8245fee4-c074-11e6-9624-052b5077bd99.png)

**Comment by emily-phet** [comment]
@arouinfar I like the color! I think the blue keys/white background is more aesthetically appealing, but the keys look less like ...keys. So I think the blue background/white keys may do more to highlight the keypresses. I would also suggestion change the wording of the first on the list to be "left or right" instead of "left and right", to be consistent with the image next to it. Otherwise, looks great, I don't think there's any need to discuss in realtime.

**Comment by arouinfar** [comment]
Thanks @emily-phet. You make an excellent case for a colored background. Now that I think about it, white keys definitely do look more key-like, which is important. @emily-phet what are the next steps for this issue? 

Here's a mockup with the updated wording. The "or" definitely makes more sense. :)
![screen shot 2016-12-12 at 2 31 34 pm](https://cloud.githubusercontent.com/assets/8419308/21117626/bd2e4bee-c077-11e6-854d-3cd365f810a7.png)

**Comment by emily-phet** [comment]
@arouinfar Unless @terracoda has any further suggestions, I believe next steps are implementation. @ @jessegreenberg let us know if you need anything else regarding the visual design.

**Comment by arouinfar** [comment]
Excellent! @terracoda if you have any further suggestions, please let me know.

@jessegreenberg the keys look like can bel be drawn in code, but if you need any illustrator assets, I'll be happy to send them your way.

**Comment by terracoda** [comment]
@arouinfar, I totally agree with @emily-phet. I prefer the white keys on the blue background. And good catch on the "or". I also think it is ready.

**Comment by terracoda** [comment]
@arouinfar, and I really like that you added color, too. Very nice touch!

**Comment by jhung** [comment]
I prefer the white keys because they resemble what most people will see in front of them. I find the blue background is a bit hard to read with the black text though (even though that colour combination is WCAG compliant).

@arouinfar If you give the right and bottom edges of the keys a thicker black stroke, it makes them look more like keys.

![untitled drawing](https://cloud.githubusercontent.com/assets/564762/21153077/f3b47f52-c136-11e6-94e3-fae945bad11a.png)

Looking good!

**Comment by arouinfar** [comment]
Thanks @jhung! Here's what'd it look like if I lightened the background color and layered a black rectangle behind each key and offset it slightly. I agree that it makes things look more key-like. As for the background color, we can easily tweak it once the dialog is implemented.

![screen shot 2016-12-13 at 12 25 35 pm](https://cloud.githubusercontent.com/assets/8419308/21155404/48448e16-c12f-11e6-9cd7-9059e46e5571.png)

**Comment by jessegreenberg** [comment]
If a screen reader is in use, the 'H' key will not work as a hot key to bring up the keyboard help menu because 'H' is commonly used to navigate page headings.  It is only working in BASE because of a specific ARIA role on the balloon.

In general, we found that global hot keys are problematic for screen reader users because most keys are used by the AT for navigation.  @emily-phet @arouinfar @terracoda is it OK if we remove the 'H key opens this dialog' row?

**Comment by terracoda** [comment]
@jessegreenberg, good catch! Yes, we will have to remove this line.

**Comment by emily-phet** [comment]
@jessegreenberg Question: I know that most keys are used by AT for navigation, but don't they (at least screenreaders) typically require a second or third key to be pressed simultaneously? For example, VO uses the H key, but you have to press Ctrl-Opt+H to activate.

**Comment by terracoda** [comment]
@emily-phet, single letter keys work as shortcuts as well.
For example JAWS uses almost every key - maybe every one: http://doccenter.freedomscientific.com/doccenter/archives/training/jawskeystrokes.htm

**Comment by jobara** [comment]
@emily-phet both JAWS and NVDA use "H" for heading navigation. 

http://webaim.org/resources/shortcuts/jaws#headings
http://webaim.org/resources/shortcuts/nvda#headings

**Comment by emily-phet** [comment]
@terracoda @jobara Thanks for the clarification. For some reason I thought in JAWS and NVDA you still used a modifier key along with "H". I couldn't find any single-key shortcuts for VO (though I'm certainly not an expert VO user). I wonder if this was an intentional choice by Apple to avoid conflicts.

As we discussed in a meeting today, let's just drop the "H" option from the dialog for now, and consider more holistically our needs for shortcuts (and possibly a PhET modifier key) a bit further down the road.

**Comment by jessegreenberg** [comment]
Here is a version of the sim with the keyboard help button and its dialog, with the 'H' key removed as mentioned by @emily-phet.

@arouinfar @terracoda can you please review the dialog in this version?  Please let me know if there are any layout changes that need to be made.

http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-dev.10/john-travoltage_en.html

The dialog is *not* accessible yet - I am working on that next!

**Comment by jessegreenberg** [comment]
Also - should the style of the 'X' close button change when the mouse is hovering over it?

**Comment by terracoda** [comment]
@jessegreenberg, the dialog looks good.

Regarding hovering over the X, I would say yes, a subtle border at the very least, or perhaps a bolder looking X? @arouinfar, might have a better suggestion. Is there anything in the design documentation for the new dialog style?

**Comment by arouinfar** [comment]
Looks good @jessegreenberg! We have not specified a hover behavior for the dialog close button, but I've added a comment to the dialog design doc to discuss it. For now, can you use the vertical border lines like the ones that appear in the navbar?

**Comment by terracoda** [comment]
@arouinfar and @jessegreenberg, I didn't mention this in my previous comment, but a keyboard focus style is needed as well on the close button. This can be the same as the hover style, or can be the same as other focus styles in the sim. For consistency, you may want to discuss this as well.

**Comment by jessegreenberg** [comment]
I will be working on this now.

**Comment by jessegreenberg** [comment]
@terracoda @jobara @jhung ignoring the accessible dialog, title, and button, do you have any preference for how the content inside this dialog should be represented in the parallel DOM?

I am thinking just a list like
```html
<ul>
  <li>Left or right arrow keys move the hand or the foot.</li>
  <li>Tab key moves the next item.</li>
  <li>Shift plus tab moves to the previous item.</li>
  <li>Escape key closes a dialog, like this one.</li>
</ul>

**Comment by jessegreenberg** [comment]
It would be most convenient if we could keep the html ```<b>``` tags for the bold content.  Would something like 

```html
<h1>Hot keys and Help</h1>
<ul>
  <li><p><b>Left or right arrow keys</b> move the hand or the foot.</p></li>
  <li><p><b>Tab key</b> moves the next item.</li>
  <li><p><b>Shift plus tab</b> moves to the previous item.</li>
  <li><p><b>Escape key</b> closes a dialog, like this one.</li>
</ul>
```

be acceptable?

**Comment by jessegreenberg** [comment]
NVDA seems to ignore ```<b>``` in chrome.

**Comment by jessegreenberg** [comment]
NVDA ignores it in Firefox too.  Ignoring seems OK to me, but I am not sure if it is important for the text weight to be presented to an AT user.

**Comment by jessegreenberg** [comment]
According to https://www.nczonline.net/blog/2013/02/12/making-an-accessible-dialog-box/

> If you have a confirmation dialog with one button to continue in one button to cancel then you may want the default focus to be on the cancel button....If you can’t figure out where to set focus, then a good starting point is to set focus to the element representing the dialog.

This would mean the entire content.  Setting focus on the container might force AT out of 'reading' mode, so I am going to start with placing focus on the close button.

**Comment by terracoda** [comment]
@jessegreenberg, how about using ```strong``` tags. In theory, they are more semantic than a ```b``` tags?
```html <h1>Hot keys and Help</h1>
<ul>
  <li><strong>Left or right arrow keys</strong> move the hand or the foot.</li>
  <li><strong>Tab key</strong> moves the next item.</li>
  <li><strong>Shift plus tab</strong> moves to the previous item.</li>
  <li><string>Escape key</strong> closes a dialog, like this one.</li>
</ul>
```

**Comment by terracoda** [comment]
@jessegreenberg, that article on accessible dialogs, though nice and thorough, is from 2013. Here is a more recent article from Paul. J. Adam at Deque Systems. Even though it is specifically on the alertdialog (simple or detail), I think it may be relevant for us.
- http://www.deque.com/blog/aria-modal-alert-dialogs-a11y-support-series-part-2/

Paul suggests deviating from the standard and
> to send focus to the first logically focusable element inside the dialog.

In our example, we only have one button, the close button. I think it is ok to set focus on the close button. In that case, it might make sense to put the close button first in the content as well.

@jhung, and @jobara , does this approach make sense when there is only one focusable item, the close button?

Note, in my earlier interviews, one user read the content in the dialog out of order (backwards), but I think most users who accessed the dialog didn't have any trouble, at lease not after we fixed a couple of obvious early problems (e.g. role=document). 

Was/is `focus` set to the close button in the BASE prototype?

Here's the link to the ARIA 1.1 Authoring Practices. I just noticed that the `dialog` item is being edited/commented.
- https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

**Comment by terracoda** [comment]
@jessegreenberg Paul J. Adam's technique for hiding the main page content is also different. I am not sure what technique is better.

**Comment by jessegreenberg** [comment]
> how about using strong tags

Sounds good!  NVDA doesn't seem to do anything with ```<strong>``` either, but we may as well us this.

**Comment by jessegreenberg** [comment]
>  I think it is ok to set focus on the close button. In that case, it might make sense to put the close button first piece of content in the dialog.

Sounds good, I will do that for now.

**Comment by jessegreenberg** [comment]
> Was/is focus set to the close button in the BASE prototype?

To my memory, in BASE focus was set on the text content, which had role=document.  Since the content had role=document, the arrow keys could still be used to read info with the virtual cursor.

**Comment by jessegreenberg** [comment]
> Paul J. Adam's technique for hiding the main page content is also different. I am not sure what technique is better.

Since we are using the Parallel DOM, we can use the ```hidden``` attribute on the container of the entire screen, which removes the content from the navigation order *and* hides from the virtual cursor. This way we don't have to worry about setting tab indices.

**Comment by jessegreenberg** [comment]
@terracoda @jhung @jobara any preferences for how the button that opens the dialog should be labelled?

**Comment by jobara** [comment]
Maybe the same as the dialog, "Hot Keys and Help" or maybe just "Help"?

**Comment by jessegreenberg** [comment]
Thanks @jobara I went with "Hot Keys and Help" for now.

**Comment by terracoda** [comment]
@jessegreenberg, @jobara, sorry for the late comment on this and sorry for my question about using the close button as being a little vague.

What I was a little uneasy about after reading the article by Paul J. Adam was setting focus to a non-interactive element (i.e. the H1 of the dialog), which would be my first choce. This is why I suggested that we set focus to the only interactive element we have in this dialog, the close button.  An interactive element was recommended by Paul J. Adam.

In a 2014 article in [Smashing Magazine] (https://www.smashingmagazine.com/2014/09/making-modal-windows-better-for-everyone/), Scott O'Hara seems to set focus to the containing frame, and then on entering the frame the first element that is read is the H1. On pressing tab the focus goes to the first focusable element within the dialog, a form element.

What I think we want for users in our case is:
1. to clearly understand that they have opened the keyboard help dialog, and that they are now in that dialog
2. to be able to use the arrow keys to read the content of the dialog at their own pace
3. to close the dialog intuitively by hitting escape or activating the close button
4. from the label of the original keyboard help button and from the heading of the dialog they should understand what the dialog is about

I see three options:
1. We stick with the current option of setting focus to the close button, and if so I think we should use the more explicit label for the close button, e.g. "Close Keyboard Help." 
2. We set focus to the H1, a non-interactive element, if this is safe to do so. In this case, we can use a the more simple content for the close button label, "Close".
3. Set focus to the dialog container and we should label the container with the H1 with aria-labeledby and set focus to the close button with the simple label, "Close".

My preference is actually option 2, but I was not sure, based on earlier discussion, if that was technically possible in our case.

**Comment by terracoda** [comment]
@jessegreenberg and @jobara, this [ARIA Dialog Example](http://accessibility.athena-ict.com/aria/examples/dialog.shtml) from Athena ICT highlights the H1 of the dialog. It works nicely in VO in Safari and in Chrome, BUT I can still navigate into the background page content without exiting the dialog...so the example is not a perfect one.

**Comment by terracoda** [comment]
@jessegreenberg, @mcking65 (Matt King) will be making a few dialog examples available soon. See the issue#103 over in [ARIA-Practices 1.1 ](https://github.com/w3c/aria-practices/issues/103#issuecomment-286573791).

Matt King also commented:

> For dialogs with lots of content that can scroll, it is good to have focus on an element in the portion that is visible when the dialog opens. That could be a heading if there are no interactive elements.

So based on this, I think we should go with option 2 in https://github.com/phetsims/john-travoltage/issues/127#issuecomment-286308965

And the close button can now actually be placed after of the content. Visually it should still be up in the right hand corner of the dialog.

**Comment by terracoda** [comment]
@jessegreenberg, based on earlier discussion in issue issue https://github.com/phetsims/a11y-research/issues/12 and yesterday's A11y Meeting (March 14), I think the label for the button that opens the keyboard information has changed from: 

- Hotkeys and Help: Tips on how to use this sim with a keyboard.

TO

- Keyboard Shortcuts: Tips on how to use this sim with a keyboard.

Also in issue 
https://github.com/phetsims/a11y-research/issues/12#issuecomment-268567162 we discussed other content for the bottom bar. 

@jessegreenberg, is the final version of the content clear? I think I should post a new summary over in https://github.com/phetsims/a11y-research/issues/12. It looks like we summarized and then made another change.

**Comment by terracoda** [comment]
@jessegreenberg, here are the new dialog examples from the aria-practices group
http://w3c.github.io/aria-practices/examples/dialog-modal/dialog.html

The examples are still undergoing a review, but they contain awesome design advice as well as working examples.

**Comment by terracoda** [comment]
@jessegreenberg, fyi, while the examples in https://github.com/phetsims/john-travoltage/issues/127#issuecomment-286980389 are excellent, and have good design advice, they still have some focus management issues.

**Comment by jobara** [comment]
@jessegreenberg for the "Hot Keys and Help" dialog, if i open it with the keyboard and press one of the arrow keys. I cannot use the esc key to close the dialog.

Steps:

1. Use the keyboard to open the "Hot Keys and Help" dialog
2. press any of the arrow keys
3. press the esc key ( Notice that the dialog doesn't close ).

I tried this using Safari 10.0.3 on macOS 10.12.3

**Comment by jobara** [comment]
@jessegreenberg the esc key also exits out of full screen. This is not mentioned in the "Hot Keys and Help" dialog. Additionally this causes some interaction issues when interacting with dialogs while the sim is in full screen.

Steps:

1. Put the sim in full screen
2. Use the keyboard to open the "Hot Keys and Help" dialog
3. press the esc key ( Notice that the sim exits full screen, and focus is lost. You can no long exit the dialog with the keyboard )

**Comment by jessegreenberg** [comment]
Thanks @jobara!  

- https://github.com/phetsims/john-travoltage/issues/127#issuecomment-291879262

Unfortunately, I can't reproduce this issue with Safari 9.0.1, OSX 10.9.5.

- https://github.com/phetsims/john-travoltage/issues/127#issuecomment-291886624

Good catch!  @terracoda @emily-phet @arouinfar should there a description in the Keyboard Help dialog that describes escape will also exit full screen mode?

> press the esc key ( Notice that the sim exits full screen, and focus is lost. You can no long exit the dialog with the keyboard )

I am using an older version of Safari and focus isn't lost when the sim exits full screen so I can still close the Dialog. But maybe the issue is that the dialog should get priority for closing over full screen mode.

**Comment by jessegreenberg** [comment]
It seems that for security reasons, you can't prevent exiting full screen when pressing 'escape'.  So we need to figure out why focus is leaving the dialog when full screen mode is turned off.

**Comment by terracoda** [comment]
@jessegreenberg and @jobara, I am losing focus all together after exiting full screen mode. I can't seem to tab to anything after exiting full screen mode. Hmm, very strange.

@jessegreenberg can you actually tell where focus is going?

**Comment by jessegreenberg** [comment]
Probably the body - @jobara do you happen to know?  I might be able to get a macOS device soon to check, but I am not sure.

**Comment by jessegreenberg** [comment]
We just tried this in Safari and Chrome in macOS Sierra 10.12.4 Beta, and we couldn't reproduce this bug.  @jobara or @terracoda can we screen share sometime so I can observe this bug?

**Comment by phet-steele** [comment]
I did not experience the problems in https://github.com/phetsims/john-travoltage/issues/127#issuecomment-291879262 or https://github.com/phetsims/john-travoltage/issues/127#issuecomment-292022579 using Chrome with macOS 10.12.4 (NOT beta)

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/john-travoltage/issues/127#issuecomment-292655108 I also just updated the machine to 10.12.4 (not beta) and could not reproduce the issue in Safari 10.1.

**Comment by jobara** [comment]
@jessegreenberg I just upgraded to macOS 10.12.4 which comes with Safari 10.1. It seems the issue is gone now. I tried before upgrading and the issue was there. It seems that this was a Safari bug, that has now been addressed.

**Comment by jessegreenberg** [comment]
Excellent, thanks very much @jobara.  Is this still part still an issue?

> @jessegreenberg for the "Hot Keys and Help" dialog, if i open it with the keyboard and press one of the arrow keys. I cannot use the esc key to close the dialog.

**Comment by jessegreenberg** [comment]
@emily-phet @terracoda @arouinfar is this part of @jobara's comment in https://github.com/phetsims/john-travoltage/issues/127#issuecomment-291886624 something that should be addressed?

> the esc key also exits out of full screen. This is not mentioned in the "Hot Keys and Help" dialog.

**Comment by jobara** [comment]
@jessegreenberg regarding ( https://github.com/phetsims/john-travoltage/issues/127#issuecomment-293008619 ) this also seems to have been fixed with the latest version of Safari.

**Comment by emily-phet** [comment]
@jessegreenberg If you're asking if we should add to the Hot Keys and Help dialog something about esc exiting full screen mode, I don't think we need to do that.

**Comment by jessegreenberg** [comment]
> https://github.com/phetsims/john-travoltage/issues/127#issuecomment-293011430

Thanks @jobara, thats great.

> https://github.com/phetsims/john-travoltage/issues/127#issuecomment-293014707

Ok, great @emily-phet, thanks.  In that case, can this issue be closed?

**Comment by emily-phet** [comment]
@jessegreenberg I think this issue can be closed. :)
