### ISSUE TITLE
Sonification licensing issue

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#129]
After build, the following comes out as a warning:

> license exception for JOHN_TRAVOLTAGE/koli_summer_site1_1way_mono.ogg: This does NOT meet the license requirements for PhET, the use is temporary until something new is created

We don't want this to be in production code, @emily-phet @jbphet should we create a new audio asset for this or move it out of master for deployment?

**Comment by jessegreenberg** [comment]
For #128.

**Comment by emily-phet** [comment]
@ariel-phet Can you weigh in here? We will need a version of the sim that can be published without sonification (as *the* John Travoltage sim, not a prototype), and another version that can be used for sonification refinement with collaborators in the Spring.

**Comment by jessegreenberg** [comment]
One option is that after #128 we can create a branch for the accessibility release and just pull sonification code (or maybe just the code that uses koli_summer_site1_1way_mono.ogg) out of the branch.  We can then then continue development in master as usual with collaborators.

**Comment by ariel-phet** [comment]
@jessegreenberg I think branching after #128 seems fine, that follows our normal RC style development correct?

**Comment by jessegreenberg** [comment]
Yes, exactly, the RC will be built off of that branch after the code using koli_summer_site1_1way_mono.ogg has been removed.  Sounds good, we will proceed with that plan.

Closing.

**Comment by jbphet** [comment]
koli_summer_site1_1way_mono.ogg is an impulse response file used to create a bit of a reverb effect on the sounds.  I just grabbed it off the web, but I could just create something similar, and should do so in order to avoid having to change the code.

**Comment by jessegreenberg** [comment]
Great, thanks @jbphet!

**Comment by jessegreenberg** [comment]
@jbphet we are getting close to an RC version for accessibility, do you think you can make a new sound in the next week?  Otherwise can I replace with an audio we already have under PhET licensing or remove usages.

**Comment by jbphet** [comment]
I'll get it done in the next couple of days.

**Comment by jbphet** [comment]
I have replaced the impulse response with one that I generated myself and updated the license file.  I think you should be good to go.  @jessegreenberg - if the build and deploy works with no licensing issues, this can be closed.

**Comment by jessegreenberg** [comment]
Thanks @jbphet, there are no more licensing issues (other than the exceptions for the image assets used in this sim).  Closing.
