### ISSUE TITLE
KeyNode types don't look sim-specific

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#142]
Presumably they should move into common code (scenery-phet?)

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
Alright, KeyNode types have been moved to scenery-phet.  Closing this issue since further review comments will continue in https://github.com/phetsims/scenery-phet/issues/288 or in other review issues in this repo.
