### ISSUE TITLE
KeyNode margin options

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#143]
In the default options:
```js
    // margins
    xOffset: 0, // margin from the left/right edge of key depending on alignment
    yOffset: 0, // margin from the top/bottom edge of key depending on alignment
```

maybe xMargin and yMargin would be a better name, given that they are documented as margins?

**Comment by jonathanolson** [comment]
Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Also on further read-through, these aren't margins (it is only added to the x/y values, so it's the opposite of a margin for e.g. the lower-right alignment).

I'd recommend either changing them to actually be margins, or changing the documentation.

**Comment by jessegreenberg** [comment]
> I'd recommend either changing them to actually be margins, or changing the documentation.

I prefer changing the documentation as margin seems to be ambiguous when the icon can be in any of 
```js
    // icon aligned in center of key by default
    xAlign: 'center', // 'left', 'center', or 'right'
    yAlign: 'center', // 'top', 'center', or 'bottom'
```

**Comment by jessegreenberg** [comment]
Although AlignBox uses optional  margins.  I will check the implementation there for consistency before continuing.

**Comment by jessegreenberg** [comment]
Since using AlignBox, they should be margins.

**Comment by jessegreenberg** [comment]
Renamed offset to margin since we are using AlignBox, and modified the documentation slightly.  Closing.
