### ISSUE TITLE
KeyNode layout

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#144]
Seems to replicate a lot of AlignBox features:
```js
var content = new AlignBox( keyIcon, {
  alignBounds: new Bounds2( 0, 0, options.minKeyWidth, options.minKeyHeight ),
  xMargin: options.xOffset,
  yMargin: options.yOffset,
  xAlign: options.xAlign, // 'left', 'center', or 'right' instead of just align
  yAlign: options.yAlign, // 'top', 'center', or 'bottom' instead of just align
  maxWidth: options.maxKeyWidth, // just a Node option
  maxHeight: options.maxKeyHeight // just a Node option
} );
```

and a Panel and extra un-filled Rectangles shouldn't be needed, just something like:
```js
this.children = [
  // background
  Rectangle.bounds( content.bounds.shifted( options.xShadowOffset, options.yShadowOffset ), {
    fill: options.keyShadowFill,
    cornerRadius: options.cornerRadius
  } ),
  // foreground
  Rectangle.bounds( content.bounds, {
    fill: options.keyFill,
    stroke: 'black',
    lineWidth: options.lineWidth,
    cornerRadius: options.cornerRadius
  } ),
  // content on top
  content
]; // possibly inlined in Node constructor call
```

Also note currently:
```js
lineWidth: options.line,
```
there is no options.line in the current code.

All code typed here not guaranteed to work, but the general concept should. Let me know if you have any questions.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
AlignBox to the rescue!  @jonathanolson AlignBox and AlignGroup have been great, I have used them elsewhere too.

Changed layout to recommendation in https://github.com/phetsims/john-travoltage/issues/144#issue-199945600, @jonathanolson would you like to review again?

**Comment by jonathanolson** [comment]
Looks good, thanks!
