### ISSUE TITLE
AccessibleFormNode

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#148]
If there's a decent potential of more behavior being added to every form, I'd suggest this gets moved to common code (so that every form would share that behavior).

If there's a low chance of more behavior being added, it could be replaced with ```new AccessibleNode( { tagName: 'form' } )``` in usages (or with Node after mixin).

Thoughts about what is best?

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
I would say low chance of more behavior being added.  No additional behavior needed in this sim, and I can't think of anything else at the moment.  This type does not seem necessary now.

**Comment by jessegreenberg** [comment]
AccessibleFormNode removed in the above commit and replaced with new ```AccessibleNode( { tagName: 'form' } )``` at the usage site.  Closing.
