### ISSUE TITLE
More abstraction for accessible components

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#149]
It may make sense long-term to think about mix-ins for specific component types.

For instance, say you have a Path that you want to be a slider in the DOM. You need:
```js
tagName: 'input',
inputType: 'range',
ariaRole: 'slider',
```
set, possibly ```parentContainerTagName: 'div'``` or others, you'll want the workaround:
```js
// Safari seems to require that a range input has a width, otherwise it will not be keyboard accessible.
this.domElement.style.width = '1px';
```
you'll want to handle the min/max/step attributes, etc., and maybe custom slider-related functions would be good (handles a Range and a Property{number}).

Now say you want to do that for a Text element.

It makes sense to be able to mix in this "AccessibleSlider" behavior into any Node, e.g.:

```
AccessibleSlider.mixin( AppendageNode ); // after the inherit
```
and
```
this.initializeAccessibleSlider( ... ); // somewhere in the constructor
```

where the mixin can handle hooking up all of the events (change/input/blur) into a Property{number} value and Property{boolean} dragged that clients can use.

Thoughts?

**Comment by jonathanolson** [comment]
Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Also I'd note that this is the typical case of mix-ins, where you need to add in behavior (acting like a slider) to any point in a normal inheritance hierarchy.

**Comment by jonathanolson** [comment]
Similar concepts apply to buttons and the sound button in JohnTravoltageView.

This would probably be worth some discussion and brainstorming with @jessegreenberg.

**Comment by jessegreenberg** [comment]
This seems like a really cool plan.

Is there a precedent for conditionally mixing something in?  For instance, say sun/HSlider mixes in ```AccessibleSlider```, which sets the accessible content and adds axon/Properties for clients.

But if in some context we want a sun/HSlider to look like
```html
<div role="slider" tabindex="0></div>
```
with a custom set of listeners and Properties, we could have changes to the HSlider prototype or other things that we don't want.

**Comment by jessegreenberg** [comment]
Or maybe we would require that sun/scenery-phet/joist/etc... must use the options in Accessibility.js mixin to set up accessible content, while sim-specific cases (like the Text element in https://github.com/phetsims/john-travoltage/issues/149#issue-200228808) would use the specific mixins such as ```AccessibleSlider```?

**Comment by jonathanolson** [comment]
> Is there a precedent for conditionally mixing something in?

As a concept in general, it's not unprecedented. In Scala, it would be
```new AppendageNode( ... ) with AccessibleSlider```
which creates a new object with that trait mixed in.

> For instance, say sun/HSlider mixes in AccessibleSlider, which sets the accessible content and adds axon/Properties for clients.

HSlider as a type would either have it mixed in or not. If the flexibility is warranted, you would either:

- Not have it mix it in, and have clients do so. This may be helpful if you need customizable mixins with parameters, e.g. ```AccessibleSlider.mixin( HSliderSubtype, { options } )```.
- Have another mixin which overrides some of AccessibleSlider's behavior.

**Comment by jessegreenberg** [comment]
> In Scala, it would be new AppendageNode( ... ) with AccessibleSlider

I see, interesting!

> This may be helpful if you need customizable mixins with parameters, e.g. AccessibleSlider.mixin( HSliderSubtype, { options } )

Yes, I think this will be the case, I like that a lot.  I am going to move this to scenery and play around with the idea there.

**Comment by jessegreenberg** [comment]
@jonathanolson I created an issue in scenery to track this since this is a longer term issue, and I am going to investigate there.  Closing this issue.
