### ISSUE TITLE
Some properties missing visibility documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#154]
For instance in AppendageNode:
```js
this.dragging = false;
```

In AppendageNode it only set dragging (never checking it), so it required a search to see if it was private (it isn't, the dragging value is used in JohnTravoltageView).

Since the part of code review guidelines included in https://github.com/phetsims/john-travoltage/issues/128 includes the documentation, it would be good to take care of for this.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
I added visibility documentation in #197, closing.
