### ISSUE TITLE
Type documentation improvements

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#155]
Many optional options objects aren't marked as optional in JSDoc.

Some functions don't have JSDoc documentation.

Some functions have JSDoc for some parameters, but not all (SparkNode's constructor)

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Also ```{Object}``` not ```{object}``` (only happens in one place).

**Comment by jessegreenberg** [comment]
I added all missing JSDoc I could find in #197. And https://github.com/phetsims/john-travoltage/issues/155#issuecomment-272591899 was fixed. Closing.
