### ISSUE TITLE
Appendage type

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#156]
Arm and Leg essentially have an implicit "interface" as they both have an angle, position and dragging boolean.

Can we have a supertype for this reason (and so type docs of {Leg|Arm} aren't necessary)?

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
I will take a look.

**Comment by jessegreenberg** [comment]
Done in the above commits, but @samreid could you please verify that tandems were passed through correctly? For this type extension I can't remember if the Appendage needs to create would need to create its own tandem.

**Comment by jessegreenberg** [comment]
Something is amiss with keyboard nav for the appendages, reassigning to myself.

**Comment by jessegreenberg** [comment]
Should be fixed in the above commits. john-travoltage passes phet-io tests in aqua, but @samreid would you mind verifying tandems in https://github.com/phetsims/john-travoltage/commit/689340bc9aed913a554de0abb4e4c85b0bc0a1af?

**Comment by samreid** [comment]
Normally for non-scenery-nodes, it is better to use tandem.createSupertypeTandem() when passing tandems to a super constructor call.  In this case it doesn't matter because the supertype isn't calling tandem.addInstance, but may still be a good change to make.  Everything else seems ok.

**Comment by jessegreenberg** [comment]
Thanks @samreid, I used tandem.createSupertypeTandem() in the supertype constructor calls.  Closing this issue.
