### ISSUE TITLE
Contains deprecated PropertySet code

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#157]
Should be removed in favor of direct Property usage.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Also, can JohnTravoltageModel's 'sound' property be renamed to soundEnabled, since when it gets passed through to things it's usually called soundEnabledProperty?

**Comment by samreid** [comment]
Should be fixed during #182

**Comment by samreid** [comment]
Fixed, closing.
