### ISSUE TITLE
AppendageNode code structure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#158]
The constructor is packed. Many functions in the constructor (like updatePosition, rotateAppendage, limitLegRotation) could be moved out of the constructor (and documented more) for readability.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
I moved the functions listed above out of the constructor, as well as some other clean up and added some documentation.  Closing.
