### ISSUE TITLE
Static functions on the prototype

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#161]
There are multiple instances of methods on objects that don't refer to the object in question and would be better as static methods, e.g. for AppendageNode:
```js
    distanceBetweenAngles: function( a, b ) {
      var dotProduct = Math.cos( a ) * Math.cos( b ) + Math.sin( a ) * Math.sin( b );
      return Math.acos( dotProduct );
    },
```
that never refers to the appendageNode. This could be transformed into a static function on the object itself, so it would be called with:
```
AppendageNode.distanceBetweenAngles( a, b );
```

Also fun fact, trig isn't needed for that function:
```js
var diff = Math.abs( a - b ) % ( Math.PI * 2 );
return Math.min( Math.abs( diff - Math.PI * 2 ), diff );
```

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
> Also fun fact, trig isn't needed for that function:

Nice!

**Comment by jessegreenberg** [comment]
I moved all functions in AppendageNode to the static block of inherit, I'll review the rest of the sim to find other cases of this.

**Comment by jessegreenberg** [comment]
I reviewed all other types, most other functions need to be added to the prototype.  The only exception was DebugPositions, which I changed to a static object. Closing.
