### ISSUE TITLE
Performance test for synchronous DOM updates

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#162]
It looks like DOM updates (somewhat necessarily) happen now in direct response to the DOM input events (both accessibility-related AND the actual mouse-moves) instead of being deferred until the animation frame.

Safari used to be bad about stalling when DOM changes happened outside of animation frames, delaying the frames a ton (sometimes multiple seconds if constantly dragging something). https://github.com/phetsims/scenery/issues/13 was somewhat of an example, but there were other cases and tests. This is one of the reasons why Scenery's Display batches all DOM changes until updateDisplay() is called from the animation frame.

We should check to make sure that whatever DOM manipulation occurs doesn't stall out the animation frame in whatever versions of Safari we care about. The bad behavior would appear to be everything "freezing" while you drag something, and then when you stop dragging it would update.

**Comment by jessegreenberg** [comment]
We have never seen this yet, but I will do some testing on a few devices to verify.

**Comment by jessegreenberg** [comment]
Tested Safari on a MacBook Air (Jordan).  I don't see any "freezing", but I do notice a pretty substantial loss of performance.  The deployed version on the site runs at a constant 60fps, a build version off of master is running at ~30fps while dragging the leg.

**Comment by jessegreenberg** [comment]
✋ 🌴 ☹️ built version I was testing was outfitted with istanbul, need to double check my testing.

**Comment by jessegreenberg** [comment]
Ok, built version on MacBook Air (Jordan) is running at 60 fps on Safari and Chrome.  Ill check some iPads next.

**Comment by jessegreenberg** [comment]
Perforamance before and after on 2 different iPads (Witten and Lave) seemed equivalent while dragging and running the sim in general.

However, @jonathanolson I am curious to know what you mean by
> It looks like DOM updates (somewhat necessarily) happen now in direct response to the DOM input events 

"somewhat necessarily".  Would you recommend that we investigate deferring all accessibility events until the animation frame anyway?

**Comment by jessegreenberg** [comment]
This is pretty stale, performance of basic PDOM updates has proven to be good in RC and other testing. We are working on other performance improvements to make sure that other DOM operations like updating bounds of accessible content is fast enough for the animation frame. Closing.
