### ISSUE TITLE
Potential sound leaks

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#164]
Every time the sound needs to be started again, it creates a new source and connects it.

Is this desired (instead of reusing the old source), and do we need to call disconnect() on anything?

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Originally applied to ChargeAmountSoundGenerator, but this is a reused pattern elsewhere.

**Comment by jbphet** [comment]
This is the way things work in Web Audio - the sound is only decode once, but a new source is created (which references the decoded sound) each time the sound is played.  Closing.
