### ISSUE TITLE
ChargeAmountSoundGenerator master gain

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#165]
masterGainControl.gain.value seems to be controlled in two different places (one when the number of items changes, and one when the soundEnabled changes), and requires soundEnabled checks in both places.

Could one gain node be used for whether sound is enabled, and another gain node (between it and everything else) for the gain that comes from how many items there are? It would seem to separate concerns a bit better, and makes it harder to introduce bugs in the future.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Additionally, this pattern is repeated elsewhere.

Can we feed all audio through a global gain node that is controlled by soundEnabledProperty, so that every individual component doesn't have to be aware of it and check?

**Comment by jonathanolson** [comment]
Also would simplify things in RandomNotePlayer and many other places.

**Comment by jbphet** [comment]
ChargeAmountSoundGenerator is gone as part of the work done for #294, closing.
