### ISSUE TITLE
Getting the audio context

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#166]
Currently, this code is essentially duplicated in a few places:
```js
var audioContext = new ( window.AudioContext || window.webkitAudioContext )();
```

It would be good to have this available somewhere global that could be accessed without the duplicated code. Scenery's Features.js would potentially be appropriate.

Additionally, PHET_CORE/detectPrefix would generally be recommended for grabbing prefixed objects, e.g.:
```
var AudioContext = detectPrefix( window, 'AudioContext' );
var audioContext = new AudioContext();
```

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jbphet** [comment]
The code for getting an audio context is now centralized in `phetAudioContext.js` in the tambo repo.  Closing.
