### ISSUE TITLE
ElectronLayerNode options

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#167]
JSDoc doesn't exist for the options or maxElectrons.

It would be particularly helpful for options to have the typical "extend with defaults" so it is easy to tell what options are supported.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Also, it seems that there is only one usage of ElectronLayerNode, and the pitchedPopGenerator seems to never be used.

Is all of the code related to pitchedPopGenerator dead code?

**Comment by jessegreenberg** [comment]
It looks like code related to pitchedPopGenerator was moved to JohnTravoltageAudio?
ElectronLayerNode:
```js
      // play the sound that indicates that an electron was added
      options.pitchedPopGenerator && options.pitchedPopGenerator.createPop(
        model.electrons.length / maxElectrons,
        model.electrons.length < maxElectrons ? 0.02 : 1.75 // longer pitch for last electron
      );
```
JohnTravoltageAudio:
```js
    // define a function that will play a sound when the count of electrons changing
    function playElectronAddedOrRemovedSound() {
      pitchedPopGenerator.createPop(
        model.electrons.length / MAX_ELECTRONS,
        model.electrons.length < JohnTravoltageModel.MAX_ELECTRONS ? 0.02 : 1.75 // longer pitch for last electron
      );
    }
```

**Comment by jessegreenberg** [comment]
I removed it from ElectronLayerNode since https://github.com/phetsims/john-travoltage/issues/167#issuecomment-279887081 shows it was moved to JohnTravoltageAudio and the option for pitchedPopGenerator was never used in JohnTravoltageView.

Closing, but @jbphet if this looks incorrect, please reopen.

**Comment by jbphet** [comment]
Removal of the pitchedPopGenerator code looks fine - this definitely appears to have been left over after consolidating much of the code into an "audio view".
