### ISSUE TITLE
Testing and code coverage

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#168]
@jessegreenberg, I'm curious what the best way to exercise all of the sim's features would be.

I'd like to run it while instrumented for checking code coverage, to potentially detect dead code.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
Sounds very useful @jonathanolson, I could investigate a way to do this, but does scenery or PhET have any such tool for un-instrumented code before I start?

**Comment by jessegreenberg** [comment]
Ah, I see istanbul in chipper might do this, I will take a look.

**Comment by jessegreenberg** [comment]
It sounds like we need a "fuzzKeyboard" or something in scenery to touch all keyboard navigation features.  I will create an issue there and assign to myself.

For this sim, I ran played with a built version of the sim that was instrumented with istanbul to produce this report:
![capture](https://cloud.githubusercontent.com/assets/6396244/22846077/04b848b6-efa3-11e6-8a09-4614e2ecefc1.PNG)

In /model/ :
![capture3](https://cloud.githubusercontent.com/assets/6396244/22846207/abe39262-efa3-11e6-91da-13237a1c7df9.PNG)

In /view/ :
![capture4](https://cloud.githubusercontent.com/assets/6396244/22846215/b255ec9e-efa3-11e6-8be0-14802be1240b.PNG)


In JohnTravoltageview, vast majority of untouched code was hidden behind a debugging query parameter.

None of the code that was untouched was related to accessibility.

**Comment by jessegreenberg** [comment]
I opened phetsims/scenery#606, @jonathanolson can this be closed?

**Comment by jessegreenberg** [comment]
Closing, but @jonathanolson if you want to discuss this issue any further please let me know.
