### ISSUE TITLE
ElectronLayerNode and electrons

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#169]
It looks like ElectronNodes wouldn't be added for pre-existing electrons.

Generally I recommend naming the function passed to electrons.addItemAddedListener, and then call it for all pre-existing electrons (for safety), e.g.:
```js
function addElectron( electron ) {
}
electrons.addItemAddedListener( addElectron );
electrons.forEach( addElectron );
```

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
Good idea @jonathanolson, done as recommended in https://github.com/phetsims/john-travoltage/issues/169#issue-200720335.  Closing.
