### ISSUE TITLE
ElectronLayerNode handling of nodes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#170]
View elements are currently being tagged on model elements, breaking the model-view separation and preventing multiple views of the same model element:
```js
added.viewNode = newElectron;
```

It's recommended to make a map in the view that maps from model elements to their corresponding view elements (usually by some model element ID).

Then when added:
```js
nodeMap[ electron.id ] = electronNode;
```
then for grabbing the view from the model:
```js
var electronNode = nodeMap[ electron.id ];
```

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jonathanolson** [comment]
Actually in this case, the assigned ```viewNode``` is never used, so that line should just be removed.

If GC issues happen in the sim (possibly due to creating IIFEs for every electron due to itemRemovedListener), the above approach would be recommended.

**Comment by jessegreenberg** [comment]
I removed the reference to the viewNode.  I tested the sim on FF and did notice some chop, but it doesn't seem too related to GC stuff.
![capture](https://cloud.githubusercontent.com/assets/6396244/22956233/07a8b220-f2de-11e6-98fd-5039b0fa0d0d.PNG)

Commenting out everything related to itemRemovedListener doesn't improve the chop.  It is very minor, and QA allowed it through. Closing.
