### ISSUE TITLE
Duplication of electron ranges

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#172]
In JohnTravoltageAudio, sound generators are given a range of how many electrons there may be, and it's always between 0 and ```JohnTravoltageModel.MAX_ELECTRONS```.

Additionally in all of those sound generators, there is either minItems/maxItems or minCharges/maxCharges (same meaning).

Can these get inlined into the generators (if it's always constant), or can we use a global range if we really want to support flexibility in the future?

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jbphet** [comment]
JohnTravoltageAudio no longer exists due to the work done for #294, closing.
