### ISSUE TITLE
JohnTravoltageAudio properties

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#174]
```js
this.timeAtCurrentFingerPosition = Number.POSITIVE_INFINITY;
```
and
```js
this.legStillTime = 0;
```
sound like the same thing (except one is for the leg, one is for the arm), but have different style names and are declared in very different places.

The following name sounded like a boolean name:
```js
this.shoeDragSoundBeingPlayed = null;
```
but it looks like {Sound|null} (documentation would help). ```this.currentDragSound``` or something similar would be a bit clearer.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jbphet** [comment]
JohnTravoltageAudio is gone due to work done for #294, closing.
