### ISSUE TITLE
Make sure all (accessibility and other) branches are merged to master

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#183]
Before starting on #182 we should make sure all accessibility branches (or development branches) are merged to master, to avoid a major hassle later on.  @jessegreenberg can you please review the open branches for this repo?  Merge and/or delete as appropriate.

**Comment by jessegreenberg** [comment]
Thanks @samreid, I pruned accessibility and other branches.  At this time, we are left with release branches, master, and branch new-assets, which I want to keep available until #121 is sorted out.  Closing.
