### ISSUE TITLE
Code status checkup

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#185]
In #182 I'm planning to instrument this simulation for PhET-iO.  However, I have seen many TODOs, undocumented methods, undocumented parameters, object attributes without visibility annotations,  which look like they may pertain to recent work in accessibility and sonification.  @jbphet and @jessegreenberg, can you please comment?

**Comment by jessegreenberg** [comment]
Indeed, @jonathanolson made issues for many of these as part of #128 (https://github.com/phetsims/john-travoltage/issues?q=is%3Aissue+is%3Aopen+label%3Adev%3Acode-review).  I will be working through many of these this week, though I may need to leave some sonification issues/TODO's to @jbphet, and I am not sure what the priority is for resolving those.

**Comment by jbphet** [comment]
I could take a pass through and clean up some of the TODOs related to sonification.  The sonification effort was expected to be something where we created some prototypes and got feedback, then refined the code, but we never really got much in the way of feedback - at least not yet - so I could change a few things and make some documentation changes that would make it a more permanent part of the code.  I'll discuss with @samreid and establish the priority of this relative to other phet-io efforts.

**Comment by samreid** [comment]
We'll wait to hear from @emily-phet if the sonification is an important part of the ETS publication deadline before deciding how to prioritize this.

**Comment by samreid** [comment]
@emily-phet said ETS does not require the sonification code.  We'll continue in the remaining open issues.
