### ISSUE TITLE
Pressing Reset All with keyboard nav does not restore any green boxes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/john-travoltage#189]
@jessegreenberg is this intentional? I encountered this in PhET-iO, then verified on master.

![jt01](https://cloud.githubusercontent.com/assets/5863899/22751168/b4cee9bc-edf0-11e6-84d1-9d4ba4e066d0.gif)

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, fixed in the above commit.
