### ISSUE TITLE
Phet-io state does not show lightning bolt during discharge

### ISSUE THREAD

**Issue by BryceAG** [phetsims/john-travoltage#195]
When the electons are going from the hand to the doorknob, the state only shows electrons disappearing, and not the lightning bolt.
It is hard to get a screenshot when the electrons are in the same spot due to delays between the state refreshing, but here you can see the electrons are moving in both, but only the first sim has the lightning.
![screenshot 2017-02-14 at 11 35 01 am](https://cloud.githubusercontent.com/assets/15327201/22943150/ab83bf64-f2a9-11e6-940a-8ec0c32c89b3.png)

related to phetsims/tasks#780

**Comment by samreid** [comment]
This is only a problem for the playback when the clock is disabled.  For customization (e.g. "launch" in the state wrapper), the spark shows correctly.

**Comment by samreid** [comment]
@jessegreenberg is working on John Travolage issues in master.  In 3 weeks or so, we'll work on rolling out another production version ready to share with our larger PhET-iO client base.

**Comment by samreid** [comment]
I think it's OK that the spark is transient and not part of the state and as mentioned above, if used for loading into a live sim, the spark will show.
