### ISSUE TITLE
John Travoltage keyboard nav not focusing on leg/arm in Safari

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#201]
@jessegreenberg 
Version 1.3.0-dev.14 - the latest stable version I believe, does not allow keyboard focus to get to arm/let so those are immovable. Can navigate to reset and sound button no problem. Not sure if this is an issue in the actual latest version of sim.

**Comment by jessegreenberg** [comment]
Sorry @emily-phet, I will take a look at this now.

**Comment by jessegreenberg** [comment]
@emily-phet this should be fixed.  Here is a new version:

http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-dev.17/john-travoltage_en.html

and its PDOM view:
http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-dev.17/john-travoltage-a11y-view.html

@emily-phet can you please verify and close this issue if fixed?

**Comment by emily-phet** [comment]
@jessegreenberg Everything is working now, thanks!
