### ISSUE TITLE
HTML Validation Issue: bgcolor attribute on body

### ISSUE THREAD

**Issue by jobara** [phetsims/john-travoltage#209]
Should set a CSS style declaration for the background color instead of using the `bgcolor` attribute.

Error: The bgcolor attribute on the body element is obsolete. [Use CSS instead](http://wiki.whatwg.org/wiki/Presentational_elements_and_attributes).
From line 31, column 1; to line 31, column 75
```
EADER↩-->↩<body bgcolor="black" style="padding: 0px; margin: 0px; overflow: hidden;">↩↩<!--
```

**Comment by jessegreenberg** [comment]
Thanks @jobara, this is going to be changed in phetsims/chipper#556 and tracked there.  Closing this issue.
