### ISSUE TITLE
Keyboard Button Label and Dialog Title - not the latest version

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#214]
Keyboard button’s label is “Hot Keys and Help”. Should be “Keyboard Shortcuts,” if the decision to change was final. Would also need to change the Title of the Dialog.

See [Accessibility Meeting](https://docs.google.com/document/d/1UTFoc_0LTQigHbu0XCLMHXsvKFYgHG7PKDVeQbvEsrI/edit#heading=h.1vu1btugkzfn) notes under March 14.

> Consensus: Lets go with “Keyboard Shortcuts”, right before publication we can review once more.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, good catch! Replaced in the above commit for the button label and the keyboard dialog title.
![capture](https://cloud.githubusercontent.com/assets/6396244/24727150/38b4dba4-1a12-11e7-97ec-45862bfac51d.PNG)
