### ISSUE TITLE
PhET Menu Button - no word "menu" in button label

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#215]
**Minor labelling Issues**
PhET Menu button, is read out as “P, H, E, T, Pop-up Button”. Wondering how to get the word “menu” in there. The three vertical dots icon is supposed to represent “menu”. Consider using “PhET Menu” as the button’s label, instead of "PhET" alone. But "pop-up" may be clear enough.

Also, are we ok, with P h E T being spelled out rather than said as a word? Likely cannot do much about this issue. Would miss-capitalizing "PhET" to "Phet" make it sound like “Fet” when read by a screen reader? Would this be better? Would it be acceptable to PhET?

**Comment by jessegreenberg** [comment]
> Consider using “PhET Menu” as the button’s label, instead of "PhET" alone.

NVDA automatically adds "Menu" to the label since it has the ```has-popup``` attribute.  Do you have a preference on whether or not to duplicate "Menu" for NVDA so that it shows up with VO?

> Also, are we ok, with P h E T being spelled out rather than said as a word? Likely cannot do much about this issue. Would miss-capitalizing "PhET" to "Phet" make it sound like “Fet” when read by a screen reader? Would this be better? Would it be acceptable to PhET?

@emily-phet do you have a preference here?

@jhung @jobara, do you know how others might handle when their brand name is not in the screen reader pronunciation lexicon? Actually, is there any way to specify your own?

**Comment by jessegreenberg** [comment]
In #212, @terracoda said
> VO does identify the pop-up as a menu.

Does that mean the first part is no longer an issue?

**Comment by terracoda** [comment]
@jessegreenberg, yes the actual list that pops up is identified as a menu in VoiceOver, but on the button, it only identifies the button as "P, H,  E, T pop-up, button." Is the current label "PhET" or "PhET Menu" in the PDOM?

The logo with the three dots communicates more than just "PhET", alone. It communicates "PhET Menu". The button label should communicate the same message as the image of the button. 

In previous code samples (https://github.com/phetsims/a11y-research/issues/13#issuecomment-265651483), the label on the button was "PhET Menu". I'd prefer the label to be "PhET Menu".

Unfortunately, this means "Menu" is heard twice in NVDA. I sure wish AT was more consistent ;-)

**Comment by terracoda** [comment]
@jessegreenberg, the final content for the PhET Menu was extensively discussed in https://github.com/phetsims/a11y-research/issues/12#issuecomment-286718839

I'll start a new issue for the content on the buttons, in case that can be done, too.

**Comment by jobara** [comment]
@jessegreenberg regarding punctuation this article seemed to have the best summary of options and caveats http://www.ssbbartgroup.com/blog/zip-z-p-z-p-forcing-correct-pronunciation-screen-readers/

If you end up trying to write out the word in such a way that sounds correct, you could look into using phonetic characters ( http://www.internationalphoneticalphabet.org/ipa-charts/ipa-symbols-with-html-codes/ ) although this would probably be confusing for a braille user or possibly someone reading character by character.

**Comment by jessegreenberg** [comment]
> but on the button, it only identifies the button as "P, H, E, T pop-up, button." Is the current label "PhET" or "PhET Menu" in the PDOM?

I see, thanks.  The current label is just 'PhET'. I will add 'Menu' so that it is heard with VoiceOver, but NVDA and JAWS users will hear something like "PhET Menu menu button, has pop-up submenu".

**Comment by jessegreenberg** [comment]
Thanks @jobara.  In that case, it seems like leaving as 'PhET' is best, and I agree that we don't want someone to find something like 'F E T' if reading character by character.

**Comment by terracoda** [comment]
@jobara thanks for that article from SSBart. 

And @jessegreenberg, I agree we do not want to spell PhET as Fet. I was wondering if Phet might work, but I think it is best not to change it. Screen readers are too diverse in their pronunciation. "John Travoltage" gets a bit mangled, too.

**Comment by terracoda** [comment]
@jessegreenberg, I'm happy if you just add "Menu" to the label.

**Comment by jessegreenberg** [comment]
Ok, I added 'Menu' to the label.  @terracoda is it OK to close this issue?

**Comment by terracoda** [comment]
Yes :-)
