### ISSUE TITLE
Shock sound effects don't seem to fire 

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#216]
Hmmm, not hearing the sound effects when John gets zapped and shocked. 

I have my volume up and the sim sound button on. Not sure if something is set wrong on my computer. I can play music on my computer and use Zoom, so not sure why I don’t hear John’s gazouch!

MacOs 10.12.3
Safari 10.0.3

**Comment by jessegreenberg** [comment]
@terracoda does this happen with or without VoiceOver? If only VoiceOver, I am wondering if this is a user setting?

I found this set of options:
![screen shot 2017-04-05 at 2 40 23 pm](https://cloud.githubusercontent.com/assets/6396244/24726043/311209d4-1a0e-11e7-8379-87f89f17eb73.png)

With Audio Ducking checked, the sound effects are much quieter with VO on.

**Comment by terracoda** [comment]
@jessegreenberg, thanks! 
I turned off audio ducking, and I can hear the sound effects with or without VoiceOver On.
With audio ducking on, I did not hear any sound effects while using Safari with or without VoiceOver. 

However, audio ducking has no effect on Chrome or Firefox. I always hear the sound effects in those browsers.

**Comment by terracoda** [comment]
@jessegreenberg, so it looks like this is a feature not a bug. Closing this issue.
