### ISSUE TITLE
Re-ordering and re-labeling of the PhET Menu items

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#218]
In https://github.com/phetsims/a11y-research/issues/12 we extensively discussed reordering the item, clarifying the label text, and adding new icons for the PhET Menu.

If time allows, is it possible to update the order and the labels, and leave the icons and help text for a later update? 

Final order and content for labels and help text copied here from https://github.com/phetsims/a11y-research/issues/12#issuecomment-286718839

- Keyboard Shortcuts: Tips on how to use this sim with a keyboard.
- PhET Menu: Tools and links for this sim.

Then the actual menu items in the the PhET Menu

-  View Options...
-  Check for Updates (check square icon with alt text "Already up to date.")
-  Take Screenshot (camera icon)
-  Full Screen (full screen icon)
-  Report Problem (email icon)
-  About this Sim...

Visual separation here
- PhET Website

**Note** there are 2 icons for Check for Updates
- Check for Updates  (exclamation triangle icon with alt text: "Update available.")

**Comment by jessegreenberg** [comment]
@terracoda I would recommend waiting and handling changes to the PhET menu at one time.  Changes like this to common components will require review from other team members and it will be more efficient to do that once.

Also, the issue list for this sim is growing and we are shooting for a release in ~2 weeks.  I don't think we will have the time to modify the PhET menu now, but we can certainly do so after the sim has been released.  @emily-phet what do you think?

**Comment by emily-phet** [comment]
@jessegreenberg @terracoda I agree with pausing on this until after JT is released. I think people will understand if the changes in the PhET menu come later.

**Comment by jessegreenberg** [comment]
Ok, thanks @emily-phet.  Closing this issue since the modifications will be continued in https://github.com/phetsims/a11y-research/issues/12.

**Comment by terracoda** [comment]
@jessegreenberg, @emily-phet ok. I agree changes that affect other sims is best to do all at once.
