### ISSUE TITLE
Does the Keyboard Shortcuts Dialog need a very brief Screen Reader Section?

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#228]
@jessegreenberg, @phet-steele, @emily-phet, FYI, I was having a lot of trouble getting the arrow keys to work with Safari and VO. But I just figured out that on my machine I have to press Command-Arrow key to operate the sliders. I have a feeling this is a VO setting that I have changed, but I am not sure. Option-Command-Arrow key also seems to work to move the sliders.

**Question:** What key presses are working in VO and Safari for others?

The confusing thing for me was that with VO on, the Arrow keys, alone, do not operate the slider at all, nor do the suggestions that VO provides.

For me, the Arrow keys, alone, move keyboard focus. And the VO help text says, "To start interacting with this slider, press Control-Option-Shift-Down-Arrow. To exit this web area, press Control-Option-Shift-Up Arrow."

If I do as VO suggests (i.e., press Control-Option-Shift-Down-Arrow), I just get "In slider" from VO and no further help. And continuing to use Control-Option-Shift-Down, does not move the slider. The arm slider works best if I just use the Command-Arrow key combination.

**Issue question:** 
I am wondering if we need a section in the keyboard shortcuts dialog that provides some minimal suggestions on how to operate the sliders when using a screen reader?

For example, something really simple like:
**Using a Screen Reader?**
While screen reader user settings vary, we suggest the following:
- With VoiceOver and Safari, use Command-Arrow keys to operate sliders.
- With NVDA and Firefox, use [[X keys]] to operate sliders.
- With JAWS and Internet Explorer, use [[X keys]] to operate sliders.
- With JAWS and Edge, use [[X keys]] to operate sliders.

The sliders are the most important interaction points in this sim, so explicitly saying how to move them when using a screen reader may be quite helpful. I took me a long time to figure out how to do it, and I think I figured it out by chance. It's possible a more experienced screen reader user would figure it out faster based on prior experience.

**Comment by terracoda** [comment]
@jobara and @jhung, what is your experience with the slider interaction? And how has slider interaction worked for screen reader users you have interviewed?

**Comment by jessegreenberg** [comment]
@terracoda it seems that when VoiceOver is on, slider interaction works like this:

- Press "Control + option + shift + down arrow" to enter slider
- Once in slider press left/right arrow keys to change slider values.
- tab away or press "control + option + shift+ up arrow" to leave it

Only the left or right arrow keys work when VO is on, which is actually OK, those are the only arrow keys listed in the keyboard help content.

**Comment by terracoda** [comment]
The arm and foot sliders are working better for me now that I use the VO keys to enter the slider and then use the arrow keys :-)

**Comment by jessegreenberg** [comment]
Excellent!  @terracoda do you still think we need this content in the about dialog?

**Comment by terracoda** [comment]
@jessegreenberg, I think we can wait and see. It's possible someone who really knows how to use VoiceOver would not have the trouble I had.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for the instructions. When I do as VO says to enter slider, the arrow keys work fine. My problem was that I kept holding the VO keys.

Closing this issue.

**Comment by terracoda** [comment]
Sorry, I did not answer the question. We may need more, but we can wait and see, especially if I was the only one having a problem.
