### ISSUE TITLE
Questions about discharge alert in JohnTravoltageA11yStrings.js

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#231]
@jessegreenberg or @jhung,  regarding Discharge Alert in  https://github.com/phetsims/john-travoltage/issues/222#issuecomment-296067662
> Electrons on body: Discharge occurred. Electrons decreased from 24 to 0

Do you have any idea why "Electrons on body: " is at the start of the discharge alert? Is that a typo? There is no parameter after the colon to for a value for the number of electrons, so I'm wondering it is a mistake.

**Comment by jessegreenberg** [comment]
Perhaps for consistency?  Usually the alerts sound like 

"Electrons on body: 5"

So maybe the initial notification of "Electrons on body" is an indication that the alert has to do with changing number of electrons.  But I don't know for certain.  Since this is a design question, removing assignment.

**Comment by jessegreenberg** [comment]
In #231 @terracoda said:
>"Electrons on body", however; could be incorporated into the actual sentence, rather than prefacing the phrase like a label. Like this:

>"Discharge occurred. Electrons on body decreased from 24 to 0."
If the sound is muted, you could even add the "Gazouch!":

>"Gazouch! Discharge occurred. Electrons on body decreased from 24 to 0."

**Comment by terracoda** [comment]
@emily-phet, sorry I responded to your comment in the wrong issue. Do you have any thoughts on the above change? Implementing the change (without the Gazouch) requires no logic, so we could wait for @jhung's return.

**Comment by jhung** [comment]
@jessegreenberg @terracoda "Discharge occurred. Electrons on body decreased from 24 to 0." works for me as a notification when a discharge occurred.

Originally it was done that way for 1. consistency, 2. it was the best compromise at the time due to the way we were handling strings.

**Comment by terracoda** [comment]
@jhung, glad this change works for you, and very glad you are back!

**Comment by jessegreenberg** [comment]
@terracoda change is in master, are we ready to close?

**Comment by terracoda** [comment]
Yes, @jessegreenberg. Closing issue.
