### ISSUE TITLE
[JAWS + IE11] All group content is read when entering a group for the first time

### ISSUE THREAD

**Issue by phet-steele** [phetsims/john-travoltage#245]
@jessegreenberg, when tabbing to the Mute Sound or Reset All Buttons from outside of their group, JAWS will read the contents of the group first, then the button you are over. For example (from memory, certainly not what is actually said):

1. Start with focus on the arm
2. Tab to the Mute Sound button
3. You will hear "Mute Sound, button. Reset All, button. Mute Sound, toggle, button." (or something). So you hear the two objects in the group followed by the object you are over.

Interestingly, when tabbing to the leg/arm you do NOT hear the entire group even though they are group the same way.

For phetsims/tasks#831.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele.  If it happened with the arm and leg I would say this is a feature.  Since it is inconsistent it seems more like a bug.

**Comment by jessegreenberg** [comment]
This also happens when you focus from the other direction.  If starting on the Keyboard Help button, you will hear

"Mute sound, toggle button." "Reset All, button"

**Comment by jessegreenberg** [comment]
The html for the Reset All button looks like
```html
<input type="button" aria-label="‪Reset All‬" id="76-137-147-173-170" style="width: 1px;">
```

I am not sure why it isn't 
```html
<button>Reset All</button>
```

**Comment by jessegreenberg** [comment]
Fixed in the above commit, but we should make sure that it doesn't change the behavior for VO and NVDA.

**Comment by jessegreenberg** [comment]
Tested on VO with Safari, NVDA with Firefox, JAWS with IE11, all is working well.
