### ISSUE TITLE
[JAWS + IE11] JAWS doesn't say anything when moving quickly through input values

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#246]
Seen on Windows 10, IE11 + JAWS. For phetsims/tasks#831. Found by @phet-steele.

When moving quickly through slider values (**not** press and hold - press and hold has its own problem #227), JAWS doesn't say anything when you reach the min/max values of the slider. Here is an example interaction:

Leg at position 0:
{right arrow} - positio...(JAWS cut off because user presses right arrow again quickly)
{right arrow} - positio...(JAWS cut off because user presses right arrow again quickly)
{right arrow} - positio...(JAWS cut off because user presses right arrow again quickly)
{right arrow} - positio...(JAWS cut off because user presses right arrow again quickly)
{right arrow} - positio...(JAWS cut off because user presses right arrow again quickly)
{right arrow} - positio...(JAWS cut off because user presses right arrow again quickly)
{right arrow} - positio...(JAWS cut off because user presses right arrow again quickly)
{right arrow} - [silence]
{right arrow} - [silence]
{right arrow} - [silence]
{right arrow} - [silence]

**Comment by jessegreenberg** [comment]
Much like #242, this is an issue with how JAWS reads things for all HTML sliders, and can be reproduced here https://jsfiddle.net/1j1y3s8p/.

I am not sure that this is even a bug or if this is the way it was designed to be read out.  @emily-phet I am going to mark this as ```wontfix```, but please let me know if you think it is worth further investigation.

**Comment by emily-phet** [comment]
@jessegreenberg I agree, marking as wontfix sounds appropriate. Hopefully if a user experiences this, they will start navigation more slowly to see what happens, and then hear readouts again.

**Comment by jessegreenberg** [comment]
Added to https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/edit, closing.
