### ISSUE TITLE
Touch on PhET menu doesn't blur focus

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#249]
This is problematic for cases like this, where the focus highlight obscures menu content:

![capture](https://cloud.githubusercontent.com/assets/6396244/25933558/d05708a0-35d4-11e7-939c-44cef60e5cab.PNG)

Mouse clicks pop focus away from the document, so this is only a problem for touch input on the PhET menu.

For https://github.com/phetsims/tasks/issues/838.

**Comment by jessegreenberg** [comment]
This isn't happening in Firefox, so this is actually a browser specific issue.

**Comment by jessegreenberg** [comment]
Edge has this problem too, and I would guess IE11 will as well.

**Comment by jessegreenberg** [comment]
IE11 has this problem for both mouse and touch events.  It looks like focus doesn't blur the active element when clicking in the sim.

**Comment by jessegreenberg** [comment]
Fixed via https://github.com/phetsims/joist/commit/c69ff41b473aa3073ed50662d8b796b8802f6759.  Leaving open to verify in a spot check in the next RC.

**Comment by phet-steele** [comment]
👍, also fixed on a touchscreen chromebook.

**Comment by jessegreenberg** [comment]
Reopening, @phet-steele noticed that the fix prevents focus from entering the PhET menu  in IE11 and Edge.

**Comment by phet-steele** [comment]
Actually, not quite there.

**Comment by phet-steele** [comment]
Oh, @jessegreenberg, you got this handled then...

**Comment by jessegreenberg** [comment]
I think we are hitting this IE11 bug
https://github.com/jquery/jquery/issues/2511

The bug does not happen in Edge.

**Comment by jessegreenberg** [comment]
Here is another report https://connect.microsoft.com/IE/feedback/details/858200/error-when-trying-to-blur-a-link-in-fullscreen-mode

**Comment by phet-steele** [comment]
Work around has IE11 work around touch inputs.
