### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#250]
A reminder to do so before the sim is published.

For https://github.com/phetsims/tasks/issues/838.

**Comment by jessegreenberg** [comment]
We are going to add an entry for John and Justin under a new "Contributors" section.

We will also want to add some QA members, and probably @emily-phet @jessegreenberg and @terracoda to Team.

@emily-phet any others?

**Comment by phet-steele** [comment]
@jessegreenberg, here is QA:

Steele Dalton, Bryce Griebenow, Ben Roberts, Oliver Orejola

**Comment by jessegreenberg** [comment]
Thanks!

**Comment by jessegreenberg** [comment]
New credits:

![capture](https://cloud.githubusercontent.com/assets/6396244/25978137/ac9cc75c-367d-11e7-8ec7-d3ca9b4c4d9b.PNG)

Look OK @phet-steele @emily-phet?

**Comment by jessegreenberg** [comment]
@arouinfar I have a vague memory that we are missing a new graphic artist that added the new head asset,  should someone else be added?

**Comment by arouinfar** [comment]
@jessegreenberg please add Mariah Hermsmeyer to the graphic arts credits.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, added.  Closing.
