### ISSUE TITLE
Keyboard Help, no max width

### ISSUE THREAD

**Issue by phet-steele** [phetsims/john-travoltage#253]
<img width="1917" alt="screen shot 2017-05-11 at 4 52 40 pm" src="https://cloud.githubusercontent.com/assets/5863899/25975231/64a9638c-366a-11e7-8236-64d8503df489.png">

Seen on macOS 10.12.4 Chrome. For phetsims/tasks/issues/838

Name: ssssssssdsdsdsdsdsdddsdfffffffffffgfggdfaflhdfaldsfhdkfjhdlkfjhaflkjdhflkadjfhdlkfjhdlkfjhdflkjahfklajfhlakjdhfkadjhflkajdfhdslkfjhadlkfjhdlkfjhadlkfjhdlfkjhdfkljhdalfkjhdalfkjdhfljdhflkajsdhflkdajfhldkjfhdklfgdlkjhglkgjhadfkjdhfkjahgkdsfgdkgjhaeuiryaewuiryewrouyfdfuihdafkjbflidabfliuwfiuehfd9f8dyf9zd8z98fhdf98a9f7yer9478rwyhib4t98yrg7ehuifb4try89eghiu4ty79grehuibty49rgeufhidbjyt4grueihfughriurw8ghobgjnrtu4389ytibhrfouyrgih4bkjtnrgefodugyuehjbjr4ioegfud8ygurhwbj4knlegidofuygh
URL: http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-rc.1/john-travoltage_en.html?stringTest=ssssssssdsdsdsdsdsdddsdfffffffffffgfggdfaflhdfaldsfhdkfjhdlkfjhaflkjdhflkadjfhdlkfjhdlkfjhdflkjahfklajfhlakjdhfkadjhflkajdfhdslkfjhadlkfjhdlkfjhadlkfjhdlfkjhdfkljhdalfkjhdalfkjdhfljdhflkajsdhflkdajfhldkjfhdklfgdlkjhglkgjhadfkjdhfkjahgkdsfgdkgjhaeuiryaewuiryewrouyfdfuihdafkjbflidabfliuwfiuehfd9f8dyf9zd8z98fhdf98a9f7yer9478rwyhib4t98yrg7ehuifb4try89eghiu4ty79grehuibty49rgeufhidbjyt4grueihfughriurw8ghobgjnrtu4389ytibhrfouyrgih4bkjtnrgefodugyuehjbjr4ioegfud8ygurhwbj4knlegidofuygh
Version: 1.3.0-rc.1 2017-05-10 21:24:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"7b0852e8","branch":"HEAD"},"babel":{"sha":"2a8bd229","branch":"master"},"brand":{"sha":"c904b097","branch":"HEAD"},"chipper":{"sha":"3c76a864","branch":"HEAD"},"dot":{"sha":"6b4ec39c","branch":"HEAD"},"john-travoltage":{"sha":"d9ac1cbc","branch":"HEAD"},"joist":{"sha":"09489aea","branch":"HEAD"},"kite":{"sha":"7d2df183","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"11406a81","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"6a4036d6","branch":"HEAD"},"scenery-phet":{"sha":"6b62b3c5","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"1c94ce39","branch":"HEAD"},"tandem":{"sha":"744bc32f","branch":"HEAD"},"vibe":{"sha":"5e8151e1","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
@phet-steele the sim passes stringTest=long.

Do our sims need to pass ```stringTest=stringTest=ssssssssdsdsdsdsdsdddsdfffffffffffgfggdfaflhdfaldsfhdkfjhdlkfjhaflkjdhflkadjfhdlkfjhdlkfjhdflkjahfklajfhlakjdhfkadjhflkajdfhdslkfjhadlkfjhdlkfjhadlkfjhdlfkjhdfkljhdalfkjhdalfkjdhfljdhflkajsdhflkdajfhldkjfhdklfgdlkjhglkgjhadfkjdhfkjahgkdsfgdkgjhaeuiryaewuiryewrouyfdfuihdafkjbflidabfliuwfiuehfd9f8dyf9zd8z98fhdf98a9f7yer9478rwyhib4t98yrg7ehuifb4try89eghiu4ty79grehuibty49rgeufhidbjyt4grueihfughriurw8ghobgjnrtu4389ytibhrfouyrgih4bkjtnrgefodugyuehjbjr4ioegfud8ygurhwbj4knlegidofuygh```?

**Comment by jessegreenberg** [comment]
Sim now passes 
```js
stringTest=stringTest=ssssssssdsdsdsdsdsdddsdfffffffffffgfggdfaflhdfaldsfhdkfjhdlkfjhaflkjdhflkadjfhdlkfjhdlkfjhdflkjahfklajfhlakjdhfkadjhflkajdfhdslkfjhadlkfjhdlkfjhadlkfjhdlfkjhdfkljhdalfkjhdalfkjdhfljdhflkajsdhflkdajfhldkjfhdklfgdlkjhglkgjhadfkjdhfkjahgkdsfgdkgjhaeuiryaewuiryewrouyfdfuihdafkjbflidabfliuwfiuehfd9f8dyf9zd8z98fhdf98a9f7yer9478rwyhib4t98yrg7ehuifb4try89eghiu4ty79grehuibty49rgeufhidbjyt4grueihfughriurw8ghobgjnrtu4389ytibhrfouyrgih4bkjtnrgefodugyuehjbjr4ioegfud8ygurhwbj4knlegidofuygh
```
![capture](https://cloud.githubusercontent.com/assets/6396244/25977672/4556d3c4-367a-11e7-8720-2eccf6ba56be.PNG)
