### ISSUE TITLE
sonification audio files increase html file size

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#258]
In 7/6/17 status meeting, I asked about how audio files for sonification where being kept out of production versions, since they have to potential to greatly increase the size of the html file.  @jbphet said that the only sim that actually contains sonification audio files is john-travoltage, which has been published to the PhET site with sonification audio, and he guessed that it increases the size by ~50K. 

Looking on the production server, here's how the size of john-travoltage has evolved:

> % ls -l */john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet  900497 May 10 12:57 1.0.0/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet  900848 May 10 12:57 1.1.0/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 1164117 May 10 12:57 1.2.0/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 1164491 May 10 12:57 1.2.1/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 1164489 May 10 12:57 1.2.2/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 1164443 May 10 12:57 1.2.3/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 1165305 May 10 12:57 1.2.4/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 1165305 May 10 12:57 1.2.5/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 1165477 May 10 12:57 1.2.6/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 2359632 May 12 14:57 1.3.0/john-travoltage_en.html
-rw-rw-r--. 1 tomcat phet 2359684 Jun 29 10:21 1.3.1/john-travoltage_en.html

So the html file has grown from 900497 to 2359684.  That's an increase of almost 1.5MB (260%), way more than 50K.  I have not confirmed that the increase is due solely to audio files.

Assigning to @ariel-phet to decide whether this is an issue.

**Comment by jbphet** [comment]
I just totaled up the audio files (which includes those that existed before sonification), and they add up to 682k.  The other 900k is probably due to the accessibility work that has gone on for John Travoltage at the same time.

The sonification in this simulation is hidden behind a query parameter, and demonstrates several different versions.  About 3/4 of these files will be removed once the sonification is finalized.  Also, Firefox now supports .mp3 format, so at some point the .ogg files can be removed.  In other words, I would estimate that the additional ~600k for sonification in this sim will be reduced to 200k or less.

**Comment by jessegreenberg** [comment]
I checked file size of built versions locally with and without accessibility features enabled:
- With a11y - 2,396,770 bytes
- Without a11y - 2,396,710 bytes

Accessible content in the DOM takes about 60 bytes.  Both files would include new strings and code for a11y but I doubt that would ad up to 900k.

**Comment by jonathanolson** [comment]
Could potentially also increase iPad memory usage.

**Comment by jbphet** [comment]
I'll build a version of this simulation with only .mp3 files, and only one version of sonification, and see what the size is.  This will give us a sense of how much sonification is likely to increase the size of a built simulation.

**Comment by jbphet** [comment]
I have let the designers know that the sonification will need to tend towards synthesized sounds and small recorded sounds (mono, max compression) in order to minimize the impact on the compiled size.  I still need to do the build test described above.

**Comment by pixelzoom** [comment]
7/13/15 dev consensus was to add this item to code-review checklist (which I did):

> -[ ] Does the html file size seem reasonable, compared to other similar sims?

**Comment by pixelzoom** [comment]
The latest dev version of this sim is even larger, so it looks like audio files are still being included:

> -rw-r--r--   1 jegr0196 physphet 2429244 Sep 20 11:46 1.4.0-dev.1/john-travoltage_en.html

Any plans to republish without audio?

**Comment by jbphet** [comment]
@emily-phet - I'm getting some questions about removing the sonification from the live version of John Travoltage.  Is this being used by anyone?  It's hidden behind the "sonification" query parameters, so it isn't turned on by default.

**Comment by emily-phet** [comment]
Is this specific question re JT still an issue? @jbphet

**Comment by jbphet** [comment]
@emily-phet - yes, it is.  A concern was expressed that this sim was published with sonification which isn't being used and is currently being redesigned.  This increases the size of the sim, which affects loading time and iPad app size.  So, the original question of "[w]ould you object to it being removed until more permanent sonification is completed?" is still open.

**Comment by emily-phet** [comment]
Hmm, sorry for the delay on this then. Going forward, I do not object to having files associated with sonification removed from deployed sims during the sonification design process - as long as this doesn't cause a problem for sonification design work. 
For the case of JT, and a few other sims where deployment with sonification is planned for Spring/Summer, it may not be worth the effort to change anything for them at this point.

**Comment by jbphet** [comment]
This should be improved, though not fully addressed, by the work done to remove the .ogg files, see https://github.com/phetsims/vibe/issues/19.

**Comment by jbphet** [comment]
This should now be fully addressed, there is lots of detail in https://github.com/phetsims/tambo/issues/28.  Closing.
