### ISSUE TITLE
A couple a11y changes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#259]
From a meeting today with @terracoda, we would recommend two changes to the a11y content so it reflects our latest design practices.

1 - Add an H2 with content "Scene Summary" above the scene summary so structure and content is consistent in all sims.
2 - Remove the ```aria-controls``` attribute from the AppendageNode, with its value that points to the alert content.  We would like to make the alert content invisible to the virtual cursor once it is read, and aria-controls is notoriously buggy.

To be discussed at the a11y meeting 9/15/17.

**Comment by zepumph** [comment]
@jessegreenberg, I'm happy to take a look at these if you don't have time. Just let me know. From today's meeting it sounds like there isn't really a timeline, just that it would be good for all PhET accessibility to be consistent.

**Comment by jessegreenberg** [comment]
Thanks @zepumph that would  be great! That is correct, we probably won't redeploy for this issue but it will be a general improvement for next time.  For part 1, we would like the sim HTML to look like this:

```html
<article tabindex="-1" id="parent-container-80-141">
    <h1 tabindex="-1" id="label-80-141">‪John Travoltage‬</h1>
    <div tabindex="-1" id="80-141">
    		<section>
    			<h2>Scene summary</h2>
    			<p tabindex="-1" id="description-80-141">John's hand is close to doorknob, and he is ready to swing his leg to rub his foot on the rug.</p>
    		</section>
                <...rest of the screen view>
```

instead of this:

```html
<article tabindex="-1" id="parent-container-80-141">
    <h1 tabindex="-1" id="label-80-141">‪John Travoltage‬</h1>
    <p tabindex="-1" id="description-80-141">John's hand is close to doorknob, and he is ready to swing his leg to rub his foot on the rug.</p>
    <div tabindex="-1" id="80-141">
       <....rest of screen view>
```

scenery-phet as an  ```AccessibleSectionNode``` which might be helpful.

**Comment by zepumph** [comment]
For number 1. I think I got everything working, but there is a misplaced 'div' that is empty, and I don't know how it got there, is this a problem?

![image](https://user-images.githubusercontent.com/6856943/30838965-350345ae-a21b-11e7-8995-dd4d04146eb7.png)

See the commit above. Also I removed the aria-controls line. Please review.

**Comment by jessegreenberg** [comment]
That div is the DOM element for AccessibleSectionNode, which would holds accessible content for any children of the AccessibleSectionNode. To get rid of the div alternative would be to create a custom Node in JohnTravoltageView with options like

```js
{
  tagName: 'p'
  parentContainerTagName: 'section',
  labelTagName: 'h2'
  accessibleLabel: 'Scene Summary'
  accessibleDescription: '...'
  prependLabels: true
}
```

But I would rather re-use AccessibleSectionNode as you did and keep the empty div. Empty static elements present no a11y issues, it seems fine to leave this div in the document.

Looks great to  me @zepumph, thanks! Closing.
