### ISSUE TITLE
re-record the "ouch" sound

### ISSUE THREAD

**Issue by jbphet** [phetsims/john-travoltage#264]
We are currently working on the enhanced sound design for John Travoltage, and have replaced the previous sound for the static discharge with a more "real" sound.  However, most everyone really likes the old voice sound, where it kind of sounds like the real JT saying, "ga-zouch".  The original recording has too much of a person making a buzz sound, though, and doesn't go well with the new electrical discharge sound.  I gave it my best shot to try to re-record this, but wasn't happy with how it came out.  @samreid - I think you made the original recording.  Would you be willing and able to try to recreate this with a clearer "ouch" and "ga-zouch" sound?  If you could create a few clips that I could try out, that would be awesome.

**Comment by samreid** [comment]
I would be honored.  I sent a wave file with several samples to @jbphet email.

**Comment by jbphet** [comment]
Assigning to @emily-phet to decide if the re-recorded versions are acceptable for the latest sound design.  They can be heard in context in [this wrapped version of John Travoltage](https://bayes.colorado.edu/dev/html/phet-io-wrapper-sonification/1.0.0-dev.62/phet-io-wrapper-sonification/john-travoltage/html/john-travoltage-sonification.html?sonificationFile=sonificationMix&accessibility).  In this version, a moderate number of charges gets JT to say "ouch" on a discharge and a large amount elicits a "ga-zouch".

**Comment by jbphet** [comment]
These sounds have been incorporated into the 1.5 release which, as of this writing, is in RC and close to publication.  The sounds have been reviewed multiple times as part of the overall sound design reviews, so I think we can safely say that they have been approved.  Closing.
