### ISSUE TITLE
New Sounds from Ashton to implement

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#265]
From Ashton's email (1/21)

Here is a new ambient electron sound that has a much better loop. (This should be played at a low volume like the last one)

https://drive.google.com/open?id=1B8KDVgu3NcEtp3ik7Fw0xz2UEorAa6or

Also I wasn’t positive which reset sound was in use so I shortened both just in case. 

https://drive.google.com/open?id=1dimcV5hiTLNLtDOIP1UCslwTl4TXhVQM
https://drive.google.com/open?id=18x1T98da2Nmbm_j5n9oqRwAf1A4CulMd
https://drive.google.com/open?id=1Bf_wmM0i6GZTuSgtj92gZEoItg5iud_t

**Comment by jbphet** [comment]
These sound were integrated in https://github.com/phetsims/phet-io-wrapper-sonification/commit/fc12181ff5bc66b067a03c99bc653ee8191b2979.

**Comment by jbphet** [comment]
This is done, closing.
