### ISSUE TITLE
branch: circular_slider

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/john-travoltage#270]
From https://github.com/phetsims/john-travoltage/issues/267, we want to allow a full circular range of motion for the arm. Once the slider reaches either end of its range, we need to jump the input to the opposite end.

This will likely last a week or two.

**Comment by mbarlow12** [comment]
branch merged to master and deleted.

**Comment by jessegreenberg** [comment]
Branch re-deleted after https://github.com/phetsims/special-ops/issues/198
