### ISSUE TITLE
Sim should use AccessibleSlider trait

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#271]
The arm/leg in this sim behaves like an `input type=range` for a11y, but this sim doesn't use our AccessibleSlider trait. a11y in this sim was done before we created it.

@mbarlow12 would you please look into  replacing the a11y implementation in AppendageNode with AccessibleSlider? Hopefully AccessibleSlider will support everything that is needed by AppendageNode, but if it doesn't let me know.

It might be helpful to do this before diving too deeply into #267.

**Comment by mbarlow12** [comment]
Thanks for the tip. I agree on this implementation before #267.

**Comment by mbarlow12** [comment]
Closing and moving on to https://github.com/phetsims/john-travoltage/issues/267.

**Comment by jessegreenberg** [comment]
Reopening, these changes were applied to the experimental branch for #267, but it would be beneficial for these changes to be in master.

I added a workaround to fix #278, but presumably merging this  with master will also fix that problem and the workaround can be removed.

**Comment by mbarlow12** [comment]
Closing now that the experimental branch has been merged.
