### ISSUE TITLE
Error message upon loading master

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/john-travoltage#280]
<b>Test Device</b>

iPad Pro

<b>Operating System</b>

iOS 11.3.1

<b>Browser</b>

Safari

<b>Problem Description</b>

@jbphet discovered that the master version of John Travoltage won't load on iOS. @zepumph, do you have any insight?

The following error is given:

```
[Error] Error: Assertion failed: Only use options.accessibility as a flag. It will not override the accessibility query parameter.
	(anonymous function) (assert.js:22)
	Sim (Sim.js:91)
	(anonymous function) (john-travoltage-main.js:54)
	phetLaunchSimulation (SimLauncher.js:44)
	doneLoadingImages (SimLauncher.js:65)
	launch (SimLauncher.js:119)
	(anonymous function) (john-travoltage-main.js:53)
	execCb (require-2.1.11.js:1650)
	check (require-2.1.11.js:866)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	(anonymous function) (require-2.1.11.js:1113)
	(anonymous function) (require-2.1.11.js:132)
	(anonymous function) (require-2.1.11.js:1156)
	each (require-2.1.11.js:57)
	emit (require-2.1.11.js:1155)
	check (require-2.1.11.js:917)
	enable (require-2.1.11.js:1143)
	init (require-2.1.11.js:774)
	callGetModule (require-2.1.11.js:1170)
	completeLoad (require-2.1.11.js:1544)
	onScriptLoad (require-2.1.11.js:1671)
```

<b>Steps to Reproduce</b>

1. Use a device that runs iOS.
2. Load John Travoltage using PhET Test or PhET Bookmarks.

<b>Visuals</b>

N/A. (It's just stuck at the splash screen. The loading bar is empty.)

<details>
<summary><b>Troubleshooting Information</b></summary>

N/A. (Can't get the troubleshooting information.)

</details>

**Comment by zepumph** [comment]
Found the culprit, this is the value being passed into sim:     

`accessibility: !platform.mobileSafari, // disable accessibility on mobile Safari until accessibility works on that platform`

but here is an assertion in `Sim.js`

   ` assert && assert( options.accessibility !== false,
      'Only use options.accessibility as a flag. It will not override the accessibility query parameter.' );`

So it seems like the flag needs to instead by of type `{true|null}` to support the assertion, or we need to change the assertion. 

Over to @jessegreenberg because he implemented this. I have no preference on how to proceed as multiple options seem like great solutions.

**Comment by jessegreenberg** [comment]
@zepumph, would you be OK if we change the accessibility query parameter to a `boolean` instead of a `flag`? It would have a default value of `false`. Display.js and Sim.js `accessibility` options are documented as `boolean` so this would align with those.

**Comment by zepumph** [comment]
I'd probably rather just remove that assert (that I wrote back in November but clearly isn't a good assertion anymore). Either would be fine with me.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, I just removed the assertion. Ill close once I verify sim can be run on iOS

**Comment by jessegreenberg** [comment]
Problem is gone.
