### ISSUE TITLE
Label for Hand position slider not being read out

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#281]
It looks like the label for the Hand position slider has been switched to a paragraph by accident.

![screen shot 2018-05-31 at 10 05 40 am](https://user-images.githubusercontent.com/1902116/40782768-f14ed428-64ba-11e8-848e-8e54fb95cdfe.png)

For the label text to be read out the text needs to be in label element associated with the slider, or in an aria-label attribute on the slider. Both the Leg swing slider and the Hand position slider should use the same labeling technique. 

I am sure this was just an accident. I just noticed this on Master on PhET Test. The live sim has a label element.

**Comment by terracoda** [comment]
@jessegreenberg, please assign priority level and developer. The live sim is fine, but I would not want this little bug to slip into production with a maintenance release.

**Comment by jessegreenberg** [comment]
Good catch @terracoda, fixed in the above commit. Here is what it looks like now:
![capture](https://user-images.githubusercontent.com/6396244/40790335-eb33c1e2-64b1-11e8-8630-6e75c0d23dcf.PNG)

**Comment by jessegreenberg** [comment]
Once #271 is done, we should have more confidence that all sliders always look the same and these bugs don't creep in. Closing.
