### ISSUE TITLE
AccessibleSlider integration requires new setter implementation for aria-valuetext

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/john-travoltage#285]
Found when addressing https://github.com/phetsims/john-travoltage/issues/284, we added the ability to pass in a custom function to produce the desired `aria-valuetext` string to be set by the AccessibleSlider. Currently, AccesibleSlider simply fills in the mapped value based on the underlying model property.

**Comment by mbarlow12** [comment]
@jessegreenberg would you be willing to review the above changes when you have a little time?

**Comment by jessegreenberg** [comment]
When I try to use the keyboard, I am hitting this assertion in Range.js
```
    assert && assert( min <= max );
```

**Comment by jessegreenberg** [comment]
If I swap min and max in `angleMotion`, the assertion goes away but the leg moves backwards:
```js
    this.angleMotion = {
      min: Util.toFixedNumber( appendage instanceof Leg ? 0 : armLimitMin, 7 ),
      max: Util.toFixedNumber( appendage instanceof Leg ? Math.PI : armLimitMax, 7 )
    };
```

**Comment by jessegreenberg** [comment]
I hit another assertion while testing, if I drag the leg all the way to its left most position (-7), then press the right arrow key, I encounter
```js
        assert && assert( range.contains( lastAngle ), 'keybaord interaction should constrain the range to: ' + range );
```

But if I remove the assertion, the sim interaction seems to behave correctly (other than https://github.com/phetsims/john-travoltage/issues/285#issuecomment-404890195).

**Comment by jessegreenberg** [comment]
Its a picky thing, but we can reduce the number of object allocations if we pull this out of constrainValue:
```js
        var range = new Range( self.angleMotion.min, self.angleMotion.max );
```

**Comment by jessegreenberg** [comment]
Sorry @mbarlow12 above comments might all be already on your radar. Changes to AccessibleSlider look very nice. The only change I made was to reformat the accessibleValuePattern assertions. One question though, with the addition of the `mappedValue` getter, can `this.accessibleMapValue` be made private?

**Comment by mbarlow12** [comment]
@jessegreenberg I made some small tweaks in the above commit so that we're no longer seeing errors. Interestingly, the appendages are almost working properly. In terms of the movement, there's a single extra step at the positive end of the range at +15 where the slider moves from the last `stepSize` to the actual end of the range.

There are also some lingering issues with the descriptions:
- There is a delay between the described slider values in the PDOM and the `formattedValue` passed to the `createAriaValueText` function.
- The descriptions don't appear on initial sim load

I've also had some additional thoughts on the `correctRounding` function. The trouble is that if the `newValue` is slightly too large or there are some floating point quirks in the calculations, `correctRounding` pulls a step from the new value. What if the function was written:

```js

  var correctRounding = function( newValue, currentValue, stepSize ) {
    var decimalPlaces = Util.numberOfDecimalPlaces( stepSize );
    stepSize *= ( newValue > currentValue ) ? 1 : -1;
    if ( Util.toFixedNumber( Math.abs( newValue - currentValue ), decimalPlaces ) > stepSize ) {
      return currentValue + stepSize;
    }
    return newValue;
  };
```

Another couple possibilities might be to either
1) have 2 a11y sliders, one for mapping `valueProperty` to the output and another where `valueProperty` and output are the same.

Or 2) have 2 'modes' for the slider set by a param or option.

Thoughts?

**Comment by jessegreenberg** [comment]
@mbarlow12 and I paired on this yesterday and got really far.

In the implementation of `correctRounding` we decided to check for deviations around the step size by ~10e-15. The only time this will be be problematic is when individual step sizes are about that large,  and devs will generally encounter rounding/precision issues with those values so this seems acceptable.

But in the end, we decided that this case needed a intermediary property anyway because the angle of the leg increases clockwise, and so the arrow keys were backwards for what they should be for that appendage. We have an intermediate NumberProperty for AccessibleSlider that tracks the position of the appendage in integer values and is mapped to its location in radians. So now we have a step size of 1.

> There is a delay between the described slider values in the PDOM and the formattedValue passed to the createAriaValueText function.

As far as we can tell, this is the last remaining issue, and we determined it to be caused by the order in which listeners on the AccessibleSlider Properties are called.

As an enhancement, we should consider using DynamicProperty's bidirectional feature instead of 
 the intermediary NumberProperty.

**Comment by mbarlow12** [comment]
@jessegreenberg I finished the updates for the slider. Things appear to be working properly after fuzzing for a while, so let me know if you find any troubles. Feel free to close as I _think_ we're good here.

**Comment by jessegreenberg** [comment]
Thanks @mbarlow12, I think we are almost there. While testing this I noticed that the appendage descriptions aren't quite working, we are missing things like "hand pointing straight up" (landmark alerts) and direction changes.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/sun/commit/9e0d3c427c9ca76e7dca388915b37d3b1daf51ee fixed the direction change portion.

**Comment by jessegreenberg** [comment]
The problem with the direction is caused because `getTextFromPosition` sets some state variables when it constructs the string, and is called twice (once for the aria-valuetext, once for the valueTextProperty.

**Comment by jessegreenberg** [comment]
I went ahead and removed valueTextProperty, with the a11y view this is no longer necessary. But now we get direction in the value text but it always comes after landmark or other, its always one change in slider value late.

**Comment by jessegreenberg** [comment]
Wait, maybe it is working correctly, comments in the code say:
```js
      if ( !isLeg && directionDescription ) {

        // if we change directions of movement (relative to the doorknob or center of carpet, that gets next priority)
        valueDescription = directionDescription;
      }
      else if ( landmarkDescription ) {

        // if we are ever on a critical landmark, that description should take priority
        valueDescription = landmarkDescription;
      }
```

But priority documentation is different than the implementation?
