### ISSUE TITLE
Ensure Home/End keys work properly

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/john-travoltage#286]
Both the max and min of the arm's `angleProperty` map to the same value (15). Thus, using Home/End, while successfully changing the underlying model property, output the same value for AT.

Adjust the mapping function to ensure a correct result where max -> 15 and min -> -15 in all circumstances.

**Comment by mbarlow12** [comment]
@jessegreenberg would you call this issue fixed in https://github.com/phetsims/john-travoltage/commit/b2cf3b7179b8491b1087b50a685c7784d3ad0057?

**Comment by jessegreenberg** [comment]
I would, thanks!
