### ISSUE TITLE
Should there be a sound when the leg reaches its motion limit?

### ISSUE THREAD

**Issue by jbphet** [phetsims/john-travoltage#296]
I was just removing the prototype sonification sound for #293, and noticed that the early version of the sound design included a "bonk" sound when the leg motion reached either the forward or backward limit.  This seemed useful to me, but we don't have it in the current sound design.  Should we?

**Comment by emily-phet** [comment]
Sim has been user tested extensively, and sounds at end points of leg slider interaction has not come up as needed. Perhaps in this particular case the description + lack of 'rubbing' sound together is sufficient to indicate end ranges of leg slider are not that intersting, so not much time is spent there...? 

I can imagine we will need this in other contexts, but let's proceed without it for JT. 

Closing.
