### ISSUE TITLE
Version history seems messed up, how should we reconcile?

### ISSUE THREAD

**Issue by jbphet** [phetsims/john-travoltage#297]
I've been publishing some dev versions of the JT sim off of master over the last few days, and I've been using the standard grunt-based tools.  The version string in `package.json` as of this writing is `"1.4.0-dev.9"`, and everything seemed to be working just fine.  However, I just went on bayes to examine the file sizes of these recent publications, and there are several directories with version numbers that are beyond 1.4.0.  Here's a screenshot:

![image](https://user-images.githubusercontent.com/3082831/44804113-a4dcde00-ab7d-11e8-8348-f214f2cb2be9.png)

These appear to be phet-io builds, and there is indeed a 1.4-phetio branch, but I'm not clear on why the version number didn't get updated in the master branch.  Maybe it was just an oversight, and it makes me thankful for our new process and tools.  The bottom line question is: How should we straighten this out?  Should I just manually update the version on master to be `1.5.0-dev.0` and pick it up from there (to leave space for additional phetio releases on the 1.4-phetio branch)?

**Comment by samreid** [comment]
Back in the "old days" when we didn't have a good policy for using one branch to support both phet and phet-io brands, PhET-iO was built from a (non-master) branch and apparently not merged back to master.  That seems like an oversight.  Continuing at 1.5.0-dev.0 sound great to me.  Can this be unlabeled from developer meeting?

**Comment by jonathanolson** [comment]
@mattpen and I would need to know about any phet-io branch changes that are related to maintenance. John Travoltage 1.4-phetio is currently set up for maintenance releases.

**Comment by jbphet** [comment]
Updated as described above and then published a new dev version 1.5.0-dev.1 (needed for sonification work) and all looks good, closing.
