### ISSUE TITLE
Part of keyboard nav is untranslatable

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#308]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/196
Part of the keyboard nav dialog does not seem to have translatable strings.
**Steps to reproduce:**
1. Enter in a string test.  Example: stringTest=rtl
2. Open the keyboard nav dialog.
3. Note that the "Hand or Foot" and "Move Hand or Foot" strings are not changed.

**Screenshots:**
![rtl](https://user-images.githubusercontent.com/41024075/46104610-0601cc80-c191-11e8-9acd-d64b763fc649.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪John Travoltage‬:‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.1/phet/john-travoltage_en_phet.html?stringTest=double
Version: 1.5.0-rc.1 2018-09-25 20:38:20 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"ea39b709","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"ed169ed3","branch":"HEAD"},"dot":{"sha":"a6af5081","branch":"HEAD"},"john-travoltage":{"sha":"81c3b843","branch":"HEAD"},"joist":{"sha":"79cf90f9","branch":"HEAD"},"kite":{"sha":"a1257832","branch":"HEAD"},"phet-core":{"sha":"2ff7b489","branch":"HEAD"},"phet-io":{"sha":"c1301ac9","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"186d07de","branch":"HEAD"},"phet-io-wrappers":{"sha":"9126d1ed","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"eb1234c9","branch":"HEAD"},"scenery-phet":{"sha":"d205340b","branch":"HEAD"},"sherpa":{"sha":"c6a137d3","branch":"HEAD"},"sun":{"sha":"6138c76e","branch":"HEAD"},"tambo":{"sha":"afb95743","branch":"HEAD"},"tandem":{"sha":"1dd1ec01","branch":"HEAD"},"vibe":{"sha":"82f7679d","branch":"HEAD"}}

</details>

**Comment by jessegreenberg** [comment]
Shoot, sorry about that. Fixing now.

**Comment by jessegreenberg** [comment]
The above commit makes these strings translatable, and will need to be merged into the release branch. Since @jbphet is doing this deploy I will pass to him but let me know if I can help.

**Comment by KatieWoe** [comment]
Looks good on 1.5.0-rc.2
