### ISSUE TITLE
LoL: Sound Continues After Pause

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#309]
**Device**
Dell Laptop
**OS**
Win 10
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/QA/issues/196
When in LoL the humming sound of the electrons continues even after the sim is paused.  If you pause in the middle of a discharge, the zap sound continues as well.
**Steps to Reproduce**
1. Enter the sim into the LoL harness and start it.
2. Add electrons.
3. Pause the sim with LoL.

**Comment by KatieWoe** [comment]
P.S. Ive been marking legends of learning pass on the testing matrix.  Should it be marked fail due to this issue?  Also, it is not restricted to firefox.

**Comment by jbphet** [comment]
@KatieWoe - in my opinion, it would be good to mark this as having failed.  In either case, I'll address it.

**Comment by jbphet** [comment]
I've implemented a solution for this where sound generation is disabled when the sim is inactive.  It works well in this context, but I think long term I'll implement a more complete solution, and I've described that in https://github.com/phetsims/tambo/issues/51.

I think this fix is sufficient for now.  I'll leave this issue open to remind me to propagate the fix to the 1.5 release branch and have it tested there on the next RC.

**Comment by jbphet** [comment]
@KatieWoe - isn't this bug a duplicate of #306?  Please let me know and, if so, close that one (not this one) since I've referenced my commits to this issue.

**Comment by KatieWoe** [comment]
Looks good 1.5.0-rc.2
