### ISSUE TITLE
Electrons not added during scrape sound

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#313]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Edge (XHTML but not necessary)
**Problem description:**
For https://github.com/phetsims/QA/issues/196
Foot may make scrape sound without adding electron.  Not restricted to edge, but sound is louder on edge which makes it easier to reproduce.  Sometimes an electron will be added, but often it won't.
**Steps to reproduce:**
1. Move foot back and forth to build up charge and position foot to left side of screen.
2. Discharge electrons.
3. Use keyboard nav to move foot toward rug one step at a time.  Stop at first scrape sound.
4. Move foot back toward left one position, then back toward rug to make the first scrape sound again.
5. Repeat and notice lack of added electrons.

**Screenshots:**
https://drive.google.com/file/d/1Di7tQvAEA4w6QfPFA4CiSbdfH7Aq30_N/view?usp=sharing

**Troubleshooting information (do not edit):**

<details>

Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.1/phet/xhtml/john-travoltage_all_phet.html
Version: 1.5.0-rc.1 2018-09-25 20:38:20 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
Language: en-US
Window: 1920x946
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"ea39b709","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"ed169ed3","branch":"HEAD"},"dot":{"sha":"a6af5081","branch":"HEAD"},"john-travoltage":{"sha":"81c3b843","branch":"HEAD"},"joist":{"sha":"79cf90f9","branch":"HEAD"},"kite":{"sha":"a1257832","branch":"HEAD"},"phet-core":{"sha":"2ff7b489","branch":"HEAD"},"phet-io":{"sha":"c1301ac9","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"186d07de","branch":"HEAD"},"phet-io-wrappers":{"sha":"9126d1ed","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"eb1234c9","branch":"HEAD"},"scenery-phet":{"sha":"d205340b","branch":"HEAD"},"sherpa":{"sha":"c6a137d3","branch":"HEAD"},"sun":{"sha":"6138c76e","branch":"HEAD"},"tambo":{"sha":"afb95743","branch":"HEAD"},"tandem":{"sha":"1dd1ec01","branch":"HEAD"},"vibe":{"sha":"82f7679d","branch":"HEAD"}}

</details>

**Comment by jessegreenberg** [comment]
Unsure if this is even a bug or if this is related to keyboard nav, but let me know if I can help.

**Comment by jbphet** [comment]
This behavior exists on the currently published version, v1.3.4, except that it's not apparent that the foot is in contact with the rug because there is no sound generation, so it's not very noticeable.  This means that I'll have to change the behavior of the model in order to fix it.

**Comment by KatieWoe** [comment]
Looks goo 1.5.0-rc.2
