### ISSUE TITLE
Sim won't load on internet explorer

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#314]
**Device**
Dell Laptop
**OS**
Win 8.1
**Browser**
Internet explorer
**Problem Description**
For https://github.com/phetsims/QA/issues/196
When attempting to open the sim in internet explorer the loading bar stalls about 1/4 of the way through and does not load.  Error in console reads:
```
SCRIPT438: Object doesn't support property or method 'createBiquadFilter'
File: john-travoltage_en_phet.html, Line: 1083, Column: 1015106
```
**Steps to Reproduce**
1. Open console on IE
2. Attempt to go to the sim

**Screenshots**
![stuck](https://user-images.githubusercontent.com/41024075/46178410-fe672400-c273-11e8-9896-ad4f6f61b436.PNG)

**Comment by phet-steele** [comment]
@jbphet here you go https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createBiquadFilter#Browser_compatibility.

**Comment by phet-steele** [comment]
@KatieWoe that link above also says this shouldn't load on an iPad. Has this sim been tested there?

**Comment by KatieWoe** [comment]
@lmulhall-phet has tested on iOS 9 and iOS 10 and marked the performance good.  I'll do a quick check on all the devices in a minute or two.

**Comment by KatieWoe** [comment]
1.5.0-rc.2 this issue seems fine but https://github.com/phetsims/john-travoltage/issues/317 has appeared.  Closing this issue.
