### ISSUE TITLE
JAWS and NVDA alerts read late

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#315]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/200
When using NVDA the alerts for discharge and the number of electrons on body no longer happen after the event or last movement themselves.  Instead, you must move the hand or foot one more time for the alert to read.
**Steps to reproduce:**
1. Turn on NVDA and use firefox
2. Using keyboard nav, scrape the foot to add charges
3. Wait to hear alert with number of charges.  It likely does not play.
4. Move the foot one more step.  Alert will play
5. Using keyboard nav, move hand until discharge happens.
6. Alert announcing discharge does not play
7. Move hand one more step
8. Alert plays

**Screenshots:**
https://drive.google.com/file/d/1zXLX9Q4FC3kyvVlwiYhoTzTzCm1cTgl0/view?usp=sharing

**Troubleshooting information (do not edit):**

<details>

Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.2/phet/john-travoltage_en_phet.html
Version: 1.5.0-rc.2 2018-10-02 23:42:17 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"ea39b709","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"ed169ed3","branch":"HEAD"},"dot":{"sha":"a6af5081","branch":"HEAD"},"john-travoltage":{"sha":"96fd9e33","branch":"HEAD"},"joist":{"sha":"dcfbcf67","branch":"HEAD"},"kite":{"sha":"a1257832","branch":"HEAD"},"phet-core":{"sha":"2ff7b489","branch":"HEAD"},"phet-io":{"sha":"c1301ac9","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"186d07de","branch":"HEAD"},"phet-io-wrappers":{"sha":"9126d1ed","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"eb1234c9","branch":"HEAD"},"scenery-phet":{"sha":"e14bfb5d","branch":"HEAD"},"sherpa":{"sha":"c6a137d3","branch":"HEAD"},"sun":{"sha":"6138c76e","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"1dd1ec01","branch":"HEAD"},"vibe":{"sha":"82f7679d","branch":"HEAD"}}

</details>

**Comment by KatieWoe** [comment]
Edit.  Just tested on Jaws and the same issue seems to occur.

**Comment by jessegreenberg** [comment]
@KatieWoe I don't think there is anything related to a second movement of the arm and leg, there is just a delay between the movement and the alert. Instead of moving the arm in the attached video, if you just wait do you still get the alert?

**Comment by KatieWoe** [comment]
@jessegreenberg I don't think so.  I can try again, but it only seems to happen after that second movement, at least when using keyboard nav.

**Comment by KatieWoe** [comment]
This issue seems to be due to a longer mount of time before the alert plays.  The instance with Jaws in particular not always playing the electron count alert unless only one movement was made still seems to be a problem.  Making a separate issue for such behavior.  Closing per @jessegreenberg

**Comment by jessegreenberg** [comment]
I changed my mind, I think we should re-open this. The delay between alerts is too abrasive, as demonstrated in the video. Ill reduce it a bit.

**Comment by jessegreenberg** [comment]
The above commit reduces the delay and things sound much better with NVDA and I assume VO. Alerts generally sound better from #310, but there are still many times where the alerts are not coming through when using JAWS with FF.

Marking as fixed pending testing, and https://github.com/phetsims/john-travoltage/commit/e301b24c5a4d2939a30d50c9c56a5896b337e637 is the commit to bring to the release branch.

**Comment by jbphet** [comment]
This should be propagated to the 1.5 release branch.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, yes this issue can be closed.
