### ISSUE TITLE
Jaws description drops and long strings of alerts

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#316]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/200 related to https://github.com/phetsims/john-travoltage/issues/315
When using Jaws the alerts for the number of electrons on body or foot position may not play if the arrow keys were held down.  Electron count plays more often, but still plays with less frequency than NVDA.  There are also still instances of long strings of alerts, sometimes the same alert repeated multiple times.
**Steps to reproduce:**
1. Turn on Jaws and use firefox
2. Using keyboard nav, scrape the foot to add charges.  Hold the arrow key down to do this.
3. Alerts are more likely to play if only a single, or few individual, scraping motions were made.
4. Repeat until behavior is seen

**Screenshots:**
https://drive.google.com/file/d/1qeltoQpYAv6OIbfCmauTCSDbLGBSMbcf/view?usp=sharing

**Troubleshooting information (do not edit):**

<details>

Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-rc.2/phet/john-travoltage_en_phet.html
Version: 1.5.0-rc.2 2018-10-02 23:42:17 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"ea39b709","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"ed169ed3","branch":"HEAD"},"dot":{"sha":"a6af5081","branch":"HEAD"},"john-travoltage":{"sha":"96fd9e33","branch":"HEAD"},"joist":{"sha":"dcfbcf67","branch":"HEAD"},"kite":{"sha":"a1257832","branch":"HEAD"},"phet-core":{"sha":"2ff7b489","branch":"HEAD"},"phet-io":{"sha":"c1301ac9","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"186d07de","branch":"HEAD"},"phet-io-wrappers":{"sha":"9126d1ed","branch":"HEAD"},"phetcommon":{"sha":"33aef589","branch":"HEAD"},"query-string-machine":{"sha":"9ae63aab","branch":"HEAD"},"scenery":{"sha":"eb1234c9","branch":"HEAD"},"scenery-phet":{"sha":"e14bfb5d","branch":"HEAD"},"sherpa":{"sha":"c6a137d3","branch":"HEAD"},"sun":{"sha":"6138c76e","branch":"HEAD"},"tambo":{"sha":"fe63321c","branch":"HEAD"},"tandem":{"sha":"1dd1ec01","branch":"HEAD"},"vibe":{"sha":"82f7679d","branch":"HEAD"}}

</details>

**Comment by jessegreenberg** [comment]
@KatieWoe and I discussed over slack. For many of the movements in the video, the arrow keys were pressed and held down, which we know JAWS has problems with (https://github.com/phetsims/john-travoltage/issues/227, and other items mentioned in https://docs.google.com/document/d/1518zv6F0odExFsodShZxwTmWNQk3civuNwtQUR-rEBs/edit). As such, we are OK with this behavior for now and will go ahead and close the issue.

Thanks for making the video and an issue for this @KatieWoe
