### ISSUE TITLE
New Screenshot

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#319]
Since https://github.com/phetsims/QA/issues/208 (1.5.0) was published and looks fairly different from the current screenshot @ariel-phet decided a new one should be made.  This is my best try at making one in the same position as the old.
@jbphet @arouinfar Does this look acceptable?  Are there any alternates that need to be done?  Do these replace the current pictures in the repo?
@mattpen What else needs to be done to put the new screenshot on the website?

**Comment by KatieWoe** [comment]
![jt screenshot](https://user-images.githubusercontent.com/41024075/46974174-83c64300-d080-11e8-8cb4-893bb5c1b3ed.png)

**Comment by arouinfar** [comment]
Looks good to me @KatieWoe!

**Comment by mattpen** [comment]
> @mattpen What else needs to be done to put the new screenshot on the website?

This should be done by the responsible dev for JT.  We'll need to add this image to the master and 1.5 branches in the JT repo then deploy a maintenance release.

**Comment by KatieWoe** [comment]
This might need to wait until @jbphet is back from vacation then.  Thanks @mattpen

**Comment by ariel-phet** [comment]
Seems fine to wait until @jbphet is back

**Comment by jbphet** [comment]
Deployed this new one in v1.5.1, looks great on the sim page.  Closing.
