### ISSUE TITLE
Public documentation of Description and Research - in John Travoltage folder

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#323]
- [x] Figure representing JT’s description design (maybe one from ASSETS demo?) [good to have by Nov. 16th-ish]

- [x] Update spreadsheet on all interviews (formal, informal, consultants, etc) conducted with JT. [Nov 2]

- [x] List of significant issues encountered in early iterations, with some ways we addressed these (though some can still be known challenges). Can link to JH's design docs as well. [good to have by Nov. 9th-ish - doesn't need to be exhaustive]

- [x] Updated description design doc, for public sharing [by Nov 30-ish]

**Comment by terracoda** [comment]
@emily-phet, do mean the main PhET Sim design folder for JT?

**Comment by emily-phet** [comment]
Yup!

**Comment by terracoda** [comment]
@emily-phet, I moved all the files in the John Travoltage A11y folder to its new home undermain PhET Sim Design.

The files were "Added" to the new location, but not removed from the old location. Is that a problem? Is that how it is supposed to work. I have verified that all the files are one and the same files.

**Comment by emily-phet** [comment]
@terracoda I think it will be problematic in the future to have duplicates. We can mark the files in the original location as 'deprecated', but this still requires someone to notice that before using them. I would prefer if the files now in the main John Travoltage folder no longer existed in the a11y folder. Is there a strong reason to still have the old docs in the original location? 

Can you make a test folder in A11y that contains two docs linking to each other. Then move those docs to the main john travoltage folder and double check that the links still work? If so, this should confirm that links within the original John Travoltage files will still work in their new location, and we can delete the old docs safely.

**Comment by terracoda** [comment]
@emily-phet, the strange thing is that the files are not "duplicates" they are the same files. I edit one in the A11y folder and the same file updates in the PhET Sim Design folder.

I don't know how to remove the file hierarchy, the path through the PhET Accessibility folder, but perhaps keeping that pathway is ok?

**Comment by emily-phet** [comment]
@terracoda oh no! that seems even more confusing. so the files will always be up to date, but existing in two places at one?!? 
We won't know (until we try in a test case) what happens if one is deleted. That means someone could delete the original file locations and possibly delete the new location? Please message Oliver and Amanda (google drive experts) and ask for their recommendation for how to get the files into the new location and remove the old files.

**Comment by terracoda** [comment]
@emily-phet, messaging our google experts. I already tested a deletion and indeed it deletes in both locations.

**Comment by terracoda** [comment]
@emily-phet, I successfully unlinked the files from their original location in the PhET Accessibility folder! We're good.

The process might be improved, but this is what I did:
- Added all files to their new location
- In new location, checked details of each file, and removed link to old location
- renamed old location folder to indicate why it was empty

Once all files are moved, we can delete the old folders all together.

**Comment by terracoda** [comment]
@emily-phet, I updated the brief design document that I had already started as an example for the team. Let me know, if you would like more details added.

**Comment by terracoda** [comment]
@emily-phet, I put my 3 JT interview notes in the correct spreadsheet.

**Comment by terracoda** [comment]
@emily-phet, I have completed an outline of design challenges, and have filled it in with many points. The last bit to fill in is a few points about the foot descriptions.

**Comment by terracoda** [comment]
@emily-phet, I can finish my thoughts on the foot tomorrow morning.

**Comment by terracoda** [comment]
@emily-phet, the JT design challenges document is ready for your review. I have completed the items in this issue. Assigning to you.

**Comment by terracoda** [comment]
@emily-phet, I just realized I just covered the interaction and description design challenges, so I added a few points about the challenges for the sonification design.
