### ISSUE TITLE
aria-valuetext doesn't update interacting with mouse

### ISSUE THREAD

**Issue by zepumph** [phetsims/john-travoltage#330]
Discovered as part of https://github.com/phetsims/scenery/issues/951. I would expect the Property passed in to AccessibleSlider to update appropriately no matter what the input modality is, but it seems like the Property only changes when using a keyboard, and thus, only the aria-valuetext in the PDOM updates when using the keyboard. 

I don't know much about this sim, but I figured this deserved a low-ish priority issue just to track the bug.

**Comment by zepumph** [comment]
Tagging @jessegreenberg so he is aware.

**Comment by jessegreenberg** [comment]
Hmm, this seems like it would be a general issue for all things that use AccessibleSlider, but Ill take a look as part of phetsims/scenery#951 review.

**Comment by jessegreenberg** [comment]
It looks like not just aria-valuetext but slider value as well.

**Comment by jessegreenberg** [comment]
It is because the AppendageNode gives the AccessibleSliider a Dynamic bidirectional Property to map from angle to input value along the slider ranges.

**Comment by jessegreenberg** [comment]
Fixed with the above commit.
