### ISSUE TITLE
Usability on small screen review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#331]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* No needed corrections noticed
* No visible pointer areas for leg or hand

Screenshots:
![Image from iOS](https://user-images.githubusercontent.com/41024075/55909270-c6cd2300-5b98-11e9-89b4-a7a0cebcbcf0.png)

**Comment by arouinfar** [comment]
https://github.com/phetsims/joist/issues/556 will discuss the possibility of automatically showing `pointerAreas` for all UI components, but according to @kathy-phet:
> I don't think its worth  spending time republishing just to make these visible though.
