### ISSUE TITLE
ShapeHitDetector needs a tandem

### ISSUE THREAD

**Issue by zepumph** [phetsims/john-travoltage#338]
ShapeHitDetector has a DragListener, which requires a tandem. When running the sim in PhET-iO brand while validating tandems, the sim fails.

@jessegreenberg let me know if I can assist in any way,.

**Comment by jessegreenberg** [comment]
Indeed, thank you and sorry about that. I expect this to be fixed in acefe10009a404ec2e73e3bc13f48c35ceba1ce7, hopefully CT will report passing tests next iteration.
