### ISSUE TITLE
rename electrons to electronGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#346]
In JohnTravoltageModel.js:

```js
  this.electrons = new PhetioGroup( tandem => {
    ...
  }, [], {
    tandem: tandem.createTandem( 'electronGroup' ),
    ...
  } );
```

`this.electrons` violates both the naming convention for PhetioGroup instances (verified with iO team on Slack), and the convention that field names must match tandem names.   It's also making it difficult to proceed with a PhetioGroup refactor in https://github.com/phetsims/tandem/issues/180.   

I'll take care of the rename to `this.electronGroup`.  Also per the iO team, group names should be singular, e.g. "electronGroup", not "electronsGroup".

**Comment by pixelzoom** [comment]
Done in the above commit. Tested unbuilt with `?fuzz` and in Studio. 

Assigning to @samreid (responsible dev) in case he wants to have a look.

**Comment by samreid** [comment]
I skimmed the commit and did not spot any trouble, thanks!  Closing.
