### ISSUE TITLE
(self-voicing) New content for Sim Overview & Hint Please! read-me buttons

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#353]
In today's Self-Voicing design meeting we iterated on the text for the Sim Overview. The original text was pulled straight from the PDOM's screen summary, and was not very relevant to the Self-Voicing experience. We created a more colorful Sim Overview for JT's Self-Voicing design. 

**For the Sim Overview button, we decided on:**
- "John Travoltage is an interactive sim. It changes as you play with it. Looks like John is leaving the house. Facing the door, he strikes a pose on the rug." 
    - Replaces: "John Travoltage is an interactive sim. It changes as you play with it. It has a Play Area and a Control Area."

There are **no changes to the Current Details content.** Here's a sample:
- "John's hand is close to doorknob, and he is ready to swing his leg to rub his foot on the rug."

**New Hint Please! content when electrons are greater than 10:**
- "Move John’s hand to see when he gets a zap."
    - Replaces: "Move John’s hand position to explore how distance from doorknob and amount of charge affect when John gets zapped."

For reference, there are several iterations in the design doc, see [Table: Read Me Button Content for Self-Voicing](https://docs.google.com/document/d/1nHzqDbRvv-By6gYK59Al345AY7D2z87Ng2im8nf4z2w/edit#heading=h.2iebrsubx3gx)

**Comment by terracoda** [comment]
Here's a screenshot for visual reference
![Screen Shot 2020-10-01 at 2 13 51 PM](https://user-images.githubusercontent.com/1902116/94838739-97475180-03f0-11eb-8f8e-ade49ecc219e.png)

**Comment by jessegreenberg** [comment]
These changes have been made, @terracoda @Matthew-Moore240 can you please review?

**Comment by terracoda** [comment]
@jessegreenberg, the new read-me button content for the Sim Overview and Hints are good.

I'll close this issue and open a new one for Current Details. @Matthew-Moore240 and I need to discuss where the extra details about the charges being discharged go.

Details like:
- where the hand is when a discharge occurs. 

I have some memory that there was access to this information in the interactive description somewhere. I just can't remember where.
