### ISSUE TITLE
(Self-Voicing) Tweak to scale describing amount of charges/electrons

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#356]
As I mentioned [here in the design doc](https://docs.google.com/document/d/1nHzqDbRvv-By6gYK59Al345AY7D2z87Ng2im8nf4z2w/edit#heading=h.45132ed7vjce) , I think we should change 
- "some" to "several"

I think "some" is too vague, and "several" can be more than "a few" and less than "a bunch of".

I also wanted to check in if there was any benefit in adding "a couple" back into the described scale?

**Comment by terracoda** [comment]
@Matthew-Moore240, I think several sounds good. 
Did we decide to leave "A couple of" off the scale? Sorry, I can't remember.
It's not super critical, it would give us 2 non-firing zones amounts on the adding charges side of things.

**Comment by Matthew-Moore240** [comment]
I think we decided not to add it. We can circle back to it if seems like an issue later.
