### ISSUE TITLE
(Self-Voicing) Add phrase about last shock to end of Current Details

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#358]
As discussed in today's Self-Voicing meeting, please add a new phrase about the last shock to the end of the current details read me button.

- For example:
“John has {{a bunch of}} electrons on his body. John's hand is {{pointing straight up}} doorknob, and he is ready to swing his leg to rub his foot on the rug. **Last shock, {{a few}} electrons discharged with hand {{close to}} door knob**.”

Be sure to clear this on a reset.

**Comment by jessegreenberg** [comment]
In order to support this the model will have to track how many electrons were discharged as well as the hand location when the last discharge ended.

**Comment by terracoda** [comment]
@jessegreenberg, I actually thought the model was already tracking the hand position when a discharge occurs, because we get response like:

- "Discharge occurred. Electrons on body decreased from 45 to 38 with hand at position -2, very close to doorknob." 

And then:
- "Discharge occurred. Electrons on body decreased from 38 to 0 with hand at position -2, very close to doorknob."

The response said discharge occurred at position negative 2, even though I kept moving the hand to position negative 1 as the discharge completed.

![Screen Shot 2020-10-13 at 2 04 44 PM](https://user-images.githubusercontent.com/1902116/95889648-3b1fee00-0d5d-11eb-86e1-e8df5df2a935.png)

**Comment by jessegreenberg** [comment]
The current implementation is just reporting those values the moment a discharge finishes in view code. What we want to support now is to remember that information and report it well after the discharge finished so it would be best to have the model keep track of this so we can retrieve it whenever the user presses the "Current Details" button. https://github.com/phetsims/john-travoltage/issues/358#issuecomment-707860075 was mostly a comment for myself to think about how to do it, it won't take long to add this to the model.

**Comment by jessegreenberg** [comment]
OK, this was added - @terracoda and @Matthew-Moore240 can you please review?

**Comment by terracoda** [comment]
Sounds good to me. What do you think @Matthew-Moore240?

**Comment by Matthew-Moore240** [comment]
Sounds good! Closing.
