### ISSUE TITLE
(PDOM) Not hearing object labels or object responses

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#374]
After latest pull, I am not hearing object labels for the hand and foot when using the keyboard with the PDOM version.
I hear context responses just fine, though.

**Comment by terracoda** [comment]
Not an immediate priority, this might be related to changes for self-voicing.

**Comment by terracoda** [comment]
Also not hearing object responses on focus or when moving arm or leg.

**Comment by jessegreenberg** [comment]
Hmm, I just tried the sim and I am not able to see this. I hear responses on focus/move no matter the input method.

**Comment by jessegreenberg** [comment]
I haven't been able to produce this, @terracoda is this still an issue for you?

**Comment by terracoda** [comment]
This issue is stale and I hear object labels (names) and object responses.
Closing.
