### ISSUE TITLE
(Self-Voicing) Hand Positions seem to be off by 1 region

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#375]
This might be related to https://github.com/phetsims/john-travoltage/issues/372
The descriptions might be off by one region. When using the keyboard (which is restricted to a single line, single circle), the string before the last stop is farthest from door knob, and then the actual last stop says, "very far from doorknob".

Then when the hand is visually at doorknob, it says "just above doorknob" and when visually just below, it says, "At doorknob."

**Comment by terracoda** [comment]
@jessegreenberg, I am not 100% sure that this is a new issue, but in previous testing of earlier versions this did not stand out to me.

**Comment by jessegreenberg** [comment]
It seems like this is only true for keyboard input. Positions generally seem correct when dragging with mouse. It is like it is reading the previous position rather than the new position in that case.

**Comment by jessegreenberg** [comment]
This is a listener order issue. Both the aria-valuetext and the  self-voicing response are linked to the appendage angleProperty. It just so happens that the response listener is called before the aria-valuetext listener, which is why it is speaking the old value.

**Comment by jessegreenberg** [comment]
OK, this shoud be fixed in the above commit.
