### ISSUE TITLE
Make first grab alert of arm/leg assertive

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#379]
From #377- sometimes you hear information about the other appendage after switching drag to the arm/leg. This would probably be resolved if the SelfVoicingUtterance was assertive for the first drag.

**Comment by jessegreenberg** [comment]
Done in the above commit. This helped in the cases I was encountering it. Would be good to hear if this helps in the cases @emily-phet noticed this as well. @emily-phet can you please check this in this dev version?

https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-dev.32/phet/john-travoltage_en_phet.html?supportsSelfVoicing&enhancedSoundInitiallyEnabled=true

**Comment by emily-phet** [comment]
yes! sounds much better.
