### ISSUE TITLE
(Self-Voicing) Tweak to Context Response for Self-Voicing Quick Menu

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#383]
Related to https://github.com/phetsims/john-travoltage/issues/382

I'm thinking new context responses would benefit all users including those who are non-visual:

When Quick Menu is opened:
- Read-me buttons & speech controls shown.

When Quick Menu is hidden, no change to response is needed. I think this still works,
- Self-Voicing Quick Menu hidden.

**Comment by terracoda** [comment]
@emily-phet and @Matthew-Moore240, do you agree on this small change to the Self-Voicing Quick Menu experience?
If so, I can assign it to @jessegreenberg and make it part of the milestone for the interviews.

**Comment by terracoda** [comment]
Actually, I already added it to the milestone, and not sure how to un-add it to the milestone.

**Comment by jessegreenberg** [comment]
This was done in the above commit @terracoda.

**Comment by terracoda** [comment]
@jessegreenberg verified in demo in zoom meeting. Closing.
