### ISSUE TITLE
(Custom Gesture Control) Adding helpful starting instructions associated with enabling gesture control

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#385]
[note - we may want to move this to a different repo, as it's more general than JT...but I wasn't sure where it should live]

When enabling the gesture control, we'll need to have a way to convey some basic information for how to use it (similar to the keyboard help intro sentence). This option also has more significant consequences for use when enabled than other options across menus (when turned on, if you don't know how to use it, it will be difficult to turn off), so we may consider a two-step option for turning on, to ensure the user really wants this.

Suggestion from @terracoda 

You have enabled custom gesture. Swipe right to move to next item, swipe left for previous item, double tap to activate or double tap for special instructions.
Continue with custom gestures enabled (button)
Continue without custom gestures (button)

We won't need this for the pre-Thanksgiving 2020 interviews, but will need to have this sorted out for the long-term of gesture control.

**Comment by jessegreenberg** [comment]
It seems like this is something that would show upon enabling from the global controls dialog, and so this may be something to consider related to that design. Removing my assignment for now since this isn't something I am working on.

**Comment by terracoda** [comment]
@emily-phet, I put the same note from https://github.com/phetsims/john-travoltage/issues/385#issue-734707859 in teh global controls document as I didn't know where else to put it.

**Comment by terracoda** [comment]
I think @jessegreenberg is correct, this will be part of the global controls or "preferences" dialog.

**Comment by terracoda** [comment]
We have custom gesture working well in both Self-Voicing versions of John Travoltage and Gravity Force Lab: Basics. How these gestures will be enabled by a learner using the sim will be part of work on the Preferences dialog.

I think work on this will continue in https://github.com/phetsims/joist/issues/652 and related issues when they come up.

I thin it is safe to close this issue.
@emily-phet, please re-open if you disagree.

**Comment by terracoda** [comment]
Also, we added helpful instructions for the sims in test flight. Maybe that's what this issue was about?
So even more reason to close :-)
