### ISSUE TITLE
(Haptics) Decrease duration of charge transfer onto body vibration

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#387]
The electron transfer onto body vibration could be slightly shorter. We want to avoid it feeling like the iOS default vibrations (e.g., the one you feel when grabbing the leg/arm), so if shortening it does that, let’s not. @jessegreenberg  – I suggest try shortening the vibration by 20% and then by 50%. See if any of these feel like the iOS default vibration (or compare the numbers, if you know the specs on that default vibration). If one or both of these feel like the iOS default vibration, scrap the whole idea. If one or both of these *do not* feel like the iOS default vibration, go with the shortest duration that *doesn’t* feel like the iOS default vibration.

**Comment by jessegreenberg** [comment]
A new version of the iOS app was deployed with a shorter vibration. Link to new version provided over slack. I ended up cutting the vibration by 50% and I think it feels nice. The iOS default vibration feels much less intense and even shorter still, so they still seem pretty different to me. Over to @emily-phet to review!

**Comment by jessegreenberg** [comment]
This was verified as working better over slack, closing.
