### ISSUE TITLE
(Custom Gesture Control) Need option to enable/disable gesture control on landing page for the sim

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#388]
Just like there's a checkbox to enable/disable self-voicing on the landing page, we'd like to have a checkbox to enable/disable gesture control on the landing page.

**Comment by emily-phet** [comment]
"Enable custom gesture"

**Comment by terracoda** [comment]
Label for switch
"Enable custom gesture"

**Comment by jessegreenberg** [comment]
I added this switch. I made it so that "Enable Custom Gesture" can only be on when "Enable Self-Voicing" is on. And the "Enable Custom Gesture" checkbox is disabled if "Enable Self-Voicing" is off.
