### ISSUE TITLE
Keyboard Shorcuts Dialog - Need ajustment to size/layout to fit new Basic Actions column

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#391]
We recently auto-added Basics Action with group navigation to all sims over in https://github.com/phetsims/scenery-phet/issues/630

We did this because the PhET menu uses group navigation, and so it made sense to just have this in all Basic Actions.

With this extra line the Basic Shortcuts column became taller and fatter. The Keyboard Shortcuts dialog looks a little crowded now, and would greatly benefit from some more space in both directions.

This would be good to address before the next publication of this sim.

Current published KB dialog:
![Screen Shot 2020-11-25 at 1 38 29 PM](https://user-images.githubusercontent.com/1902116/100260296-d17e2c80-2f23-11eb-9a79-60686779b9cd.png)

Somewhat crowded version with group navigation on master:
![Screen Shot 2020-11-25 at 1 29 20 PM](https://user-images.githubusercontent.com/1902116/100260367-e35fcf80-2f23-11eb-9b9a-438f26287225.png)

**Comment by terracoda** [comment]
@emily-phet, @jessegreenberg, and @zepumph, just putting this sim on your radar. I hope I have the right label so this can be addressed before the next maintenance release for this sim.

**Comment by zepumph** [comment]
This one will make sure it is addressed before next publication from master. Hopefully together our labels hate the right message.

**Comment by jessegreenberg** [comment]
Note to self:
Dialog options for this are `ySpacing` for vertical space between title and content and `bottomMargin` for spacing between content and bottom of dialog. Spacing between columns is `columnSpacing` of TwoColumnKeyboardHelpContent.

**Comment by terracoda** [comment]
@jessegreenberg and I met and experimented with spacing. The issue stems mainly from the fact that there is very little content in the left column, and all content is centered under the heading.

We decided to leave as is. It looks better a little crowded than it does when we put extra space in between the columns.

Closing.
