### ISSUE TITLE
(Self-Voicing) New region for electrons on body

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#395]
In #377 we removed "Rubbing" from the electrons on body response.

We also agreed on (March 16 Self-Voicing design meeting) to add a new first region:
- "{{A couple}} electrons on body." (1-4 charges)

The "A few" comes after for 5-10 or whatever the current threshold is.

When electrons get to "Several" which I think is 10, there is the potential of a shock. 

Adding to milestone, but not critical.

**Comment by jessegreenberg** [comment]
@terracoda @Matthew-Moore240 here is a new version with changes listed above. Can you please review?

https://phet-dev.colorado.edu/html/jg-tests/john-travoltage_en_phet.html?supportsSelfVoicing

**Comment by terracoda** [comment]
Region sounds awesome to me!
