### ISSUE TITLE
(Voicing) Keyboard Shortcuts dialog

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#400]
@jessegreenberg, there is a similar issue for GFLB, see https://github.com/phetsims/gravity-force-lab-basics/issues/267

We'll need a similar voicing version of the Keyboard Shortcuts dialog for John Travoltage's re-publication with Voicing.

Based on what I posted in GFLB, these are the blocks I propose for John-Travoltage
![Screen Shot 2021-04-07 at 2 17 29 PM](https://user-images.githubusercontent.com/1902116/113905007-43596300-97ad-11eb-8134-951b0ff780e9.png)

**Comment by terracoda** [comment]
@jessegreenberg, adding this to first publication milestone.
Let me know if you have any questions. I am going to adjust the date of the milestone.

**Comment by jessegreenberg** [comment]
Voicing has been added to the keyboard help dialog. It was quite a bit easier for now to add "Hand or Foot" text to the "Move hand or Foot" reading block so I did that for now. @terracoda can you please review? https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.1/phet/john-travoltage_en_phet.html?supportsVoicing

**Comment by terracoda** [comment]
This sounds and looks great.

I one have a concern that if I tab out of the dialog and get into the browser controls, I can seem to get back into the sim with Tab key presses. I will open a new issue for this.
