### ISSUE TITLE
Light blue on top of screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#411]
For https://github.com/phetsims/QA/issues/645. iPadOS with voicing.
When the iPad is in portrait mode and the voicing tool bar is open, the top of the sim seems to be blue.
![9FF06C5D-B7AE-424C-8144-C847E6847380](https://user-images.githubusercontent.com/41024075/117733110-3f56a180-b1ae-11eb-8be4-354ffbf4e55d.png)

**Comment by KatieWoe** [comment]
You can see this on Laptop browsers if the window is made tall and skinny enough.
<img width="535" alt="tallenoughblue" src="https://user-images.githubusercontent.com/41024075/117878492-12b09180-b263-11eb-9ce9-aed6399911b6.png">

**Comment by jessegreenberg** [comment]
The background is just an image and it doesn't take up the entire screen space. The background color is blue for some reason, I am not sure why. I don't think we can modify the artwork, but we could make the background color match the wall color so it isn't as noticeable.

**Comment by jessegreenberg** [comment]
I changed the background color so it looks a better. The background color extends below the floor though, when I squeeze the sim down very narrow the brown is shown below the flooor:
![image](https://user-images.githubusercontent.com/6396244/121605328-37db2000-ca1a-11eb-9dcf-bae8f6892fff.png)

But for usable screen sizes it looks better and the blue rectangle is gone. Calling that good, closing.
