### ISSUE TITLE
Hidden toolbar reads out before rest of sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#415]
For https://github.com/phetsims/QA/issues/645. Seen on iPadOS Safari with mobile VO.
When you start reading from the top (swipe two fingers up), even when the toolbar is hidden, the toolbar is read before everything else, including the welcome message.

https://user-images.githubusercontent.com/41024075/117888889-ef401380-b26f-11eb-88ab-214146eb51a4.MOV

**Comment by jessegreenberg** [comment]
It looks like the toolbar is visible in the PDOM on sim load, it does't hide until it is open/closed again.

**Comment by jessegreenberg** [comment]
OK, this is fixed in the above commit.
