### ISSUE TITLE
Voicing sim does not load on app

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#418]
I did a quick check on 1.6.0-preferences.7 on the android app (Galaxy Tab A) and the sim did not load in the app.

**Comment by KatieWoe** [comment]
I'm having trouble getting the right version of the app on the chromebook for some reason, in order to test it there. @mattpen if you are able to help out I would appreciate it.

**Comment by KatieWoe** [comment]
Thanks for the help Matt. This is also impacting the sim on the app on Chromebook.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, I think I have a better way to handle this. Can you please test with this version?

https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.13/phet/john-travoltage_en_phet.html

I expect the sim to load in the app, but the Voicing feature should be disabled in this case (not in available from Preferences).

**Comment by KatieWoe** [comment]
Sim ran on the app on the tablet. Voicing didn't work, but the tab was still available, it just didn't do anything when on

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, glad its running. Sorry I mispoke, the **tab** should be available, but the Voicing section should not be. It should look like this:
![image](https://user-images.githubusercontent.com/6396244/120027791-d2bb0f80-bfc1-11eb-8552-6f6aae70fb90.png)

Can you please confirm?

**Comment by KatieWoe** [comment]
That is not what it looks like. It looks like the other versions, with all the voicing options. But turning it on does nothing.

**Comment by jessegreenberg** [comment]
Thanks! That is not working as I would expect, I will take a look at that.

**Comment by jessegreenberg** [comment]
I am not too sure how to debug the sim in the app, but I am going to try to tether my phone running the App to my desktop and see if desktop Chrome can pick up the WebView running in the app.

**Comment by jessegreenberg** [comment]
When I did this, I saw that the window.SpeechSynthesis was not defined in the webview, which is what I would expect. Maybe something is wrong with the drawing code for the tabs.

**Comment by jessegreenberg** [comment]
I think this is fixed, @KatieWoe can you please check to verify that Voicing is not available on this platform, and nothing about it shows up in the Preferences Dialog?

https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.16/phet/john-travoltage_en_phet.html

**Comment by KatieWoe** [comment]
This looks mostly ok on both the tablet and the Chromebook. I did notice that on one tab text was centered, and on another it was left justified.
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/120555963-13979780-c3b9-11eb-81af-21e5e8e35ce0.jpg)
![Image from iOS](https://user-images.githubusercontent.com/41024075/120555966-14302e00-c3b9-11eb-92e3-5c093c7571a6.jpg)

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, layout fixed in the above commit. I think that is it for this issue since it was verified to load correctly from the webview.
