### ISSUE TITLE
Don't always hear "just above" and "just below" door knob during interaction

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#421]
Using https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.6/phet/john-travoltage_en_phet.html

on MacOS 10.13.6 

I am not always hearing the "just above" and "just below" locations.

Not sure why. It might be an artifact of the original interactive description's aria-value text implementation.

I hear the correct position on focus. Just sometimes as I pass the doorknob, I don't hear the first position above or below when passing.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, fixed in the above commit. caused by a silly mistake of mine. Can you please verify it is fixed in 
https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.9/phet/john-travoltage_en_phet.html?

**Comment by terracoda** [comment]
Hmm, I though I already verified this issue last week. 
It sounds good. Thanks @jessegreenberg, closing.
