### ISSUE TITLE
Voicing crashes the browser in macOS + Firefox

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#422]
Found while testing for #419, in macOS + Firefox the the browser crashes frequently when the Voicing feature is enabled. Basic speech works ok https://mdn.github.io/web-speech-api/speak-easy-synthesis/, so something about way we are using the feature is causing the crash.

**Comment by jessegreenberg** [comment]
Just played with the sim for ~10 minutes to see if it happens at a particular time, and got it to occur twice. The first time it when I read the first reading block. The second time was 10 minutes later when electrons were discharged.

**Comment by jessegreenberg** [comment]
To try lots of speech requests I did something like this, where I added the ResetAllButton to the window and then did
```js
window.setInterval( () => {
 window.resetAllButton.buttonModel.fire()
), 300 ).

Every 300 ms I hear "Reset..." Then it gets interrupted by the next "Reset". Up to 500 requests and no crash.

**Comment by jessegreenberg** [comment]
I had the sim fuzz for three minutes without Voicing, so I think that confirms that Voicing is the cause.

**Comment by jessegreenberg** [comment]
OK, I found a way to get it to crash relatively consistently - spam the Toolbar chevron key with spacbar presses to rapidly open and close the toolbar.

**Comment by jessegreenberg** [comment]
Adding the chevron button to the window and spamming it with
```js
var i = 0;
setInterval( () => {
  console.log( i++ )
  window.testButton.buttonModel.fire()
}, 200 )
```

Gets it to crash in 2 - 80 fires.

**Comment by jessegreenberg** [comment]
Now that I can get it to happen easily, I am going to try to find what is causing the crash to see if we can prevent it.

- I tried wrapping `this.synth.cancel()` with `this.synth.pause()` and `this.synth.resume()` to see if that would change something. Didn't work.
- I tried removing `this.synth.cancel()` entirely from webSpeaker.speak and after 57 speech requests I got a macOS rainbow wheel of doom. Maybe something about having lots of utterances in the SpeechSynthesis queue is causing a problem here. Not sure if it is related to the bug of this issue.

**Comment by jessegreenberg** [comment]
I read about [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to offload the speech, but the window and `speechSynthesis` are not available in a web worker, so we can't do that.

**Comment by jessegreenberg** [comment]
I am not sure how to proceed, I can't think of a workaround and I don't see a good solution. Other things I considered.
1) Stop simulation motion during speech. Seems like it would make a terrible experience.
2) We submit a bug report to Firefox about speechSynthesis crashing the browser. Hopefully we can get this to happen in an example outside of PhET. 
3) We disable Voicing in macOS Firefox.

**Comment by jessegreenberg** [comment]
@terracoda said on slack that she uses macOS and Firefox. @terracoda would you mind testing to see if this happens for you?

@KatieWoe would you also be able to try this on macOS Firefox to see if it ever crashes for you? That might help us determine how far we need to go here.

I can get it to most consistently crash by pressing the Toolbar's Open/Close button. But also seeing it crash sometimes when charges are being added/removed from the body.

Link to latest:
https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.12/phet/john-travoltage_en_phet.html

**Comment by terracoda** [comment]
Using MacOS 10.13.6 and Firefox 88.0.1 (64-bit) I used JT with mouse and keyboard and tried to do several things really fast:
- toggled on/off switches
- played and stopped Quick Info button
- rubbed foot fast and slow
- moved hand fast and slow
- caused big discharges and partial discharges
- toggled the Toolbar on and off using the Toolbar button and also the Toolbar switch in the Preferences Menu
- toggled Voicing features and sound features on and off
- quickly moved through Preferences Menu

I didn't experience any crashes.

**Comment by KatieWoe** [comment]
I played around for a bit (5-10 min) on MacOS 11.4 Firefox 88.0.1 and didn't see a crash. @jessegreenberg let me know if you want me to look at an older OS or test on 11.4 for longer.

**Comment by jessegreenberg** [comment]
Thanks for testing @KatieWoe that is good news. I think this issue is related to performance and the crash happens for me during high cpu load. I have a MacBook from 2013 with 2.4 GHz dual-core i5 processor. Would you mind noting the specs of your apple device for comparison?

**Comment by KatieWoe** [comment]
MacBook Pro 2016. 2.9 GHz Quad-Core Intel Core i7.

**Comment by jessegreenberg** [comment]
Cool, thanks. @terracoda would you mind noting the same info from your machine?

**Comment by terracoda** [comment]
- Mac OS Version 10.13.6
- Mac Book Pro (Retina, 13-inchm, Early 2015) 
- Processor 2.9 GHz Intel Core i5
- Memory 8 GB 1867 MHz DDR3
- Graphics Intel Iris Graphics 6100 1536 MB

**Comment by jessegreenberg** [comment]
Thanks, that is helpful. Both of those devices are newer/faster than the one I have. Over slack I asked if @KatieWoe had access to an  older/slower mac and she said yes, so I asked her to check if there was any crashing there.

**Comment by jessegreenberg** [comment]
@terracoda also mentioned she had access to a slower/older device and volunteered to test it there to see if it happens.

**Comment by KatieWoe** [comment]
Oldest readily available Mac is a MacBook Pro 2011, 2.3 GHz intel Core i5. I need to give it a bit to charge up, then will test to see if the firefox problem can be reproduced with it. Will test on OS 10.12.

**Comment by terracoda** [comment]
On terracoda's Macbook Air - no crashing
- masOS Mojave Version 10.14.6
- Macbook Air, 11-inch, early 2015
- Processor 1.6 GHz Intel Core i5
- Memory 4 GB 1600 MHz DDR3
- Graphics Intel HD Graphics 6000 1536 MB

FF version - 88.0.1 (64-bit)

**Comment by KatieWoe** [comment]
I didn't get it to crash on the older device, but it definitely had to work hard and the fan was getting pretty noisy.

**Comment by terracoda** [comment]
On terracoda's old Macbook Pro - no crashing
- Macbook Pro (13-inch, Mid 2010)
- MacOS OS X Yosemite, version 10.10.5
- Processor 2.66 GHz Intel Core 2 Duo
- Memory 8 GB 1067 MHz DDR3
- Graphics NVIDIA GeForce 320M 256 MB

Testing on Firefox 
- version 73.0.1 (64-bit) - no crashing 
- then since I was connected to the internet
- version 77.0.1 (64-bit), - Firefox crash when I enabled Voicing in Prefs Menu. Sim was already loaded in updated browser. I tabbed to Voicing on/off button, and then couldn't tab any further. I just got the Mac pin-wheel until I opened a new Finder window and killed Firefox.
- Still in 77.0.1, using the mouse, I clicked Voicing on, then when I clicked the Toolbar on/off to off FF crashed.
- version 78.10.1esr (64-bit) - no crashing in this version

The reason I tested in 3 versions is that I haven't connected this computer to the internet in a long time, so 73 was what was on before FF auto-updated version, then 77 was what it auto-updated to first and then FF asked to restart again for another update, and it auto-updated to 78 esr.

There is no crashing in this last version.

**Comment by jessegreenberg** [comment]
OK thanks @KatieWoe and @terracoda. @BLFiedler also mentioned today that he will keep an eye out for whether this is prevalent in the survey he puts out.

So to summarize, it sounds like the crashing is rare, but we have now seen it on two devices with older CPUs. I still think it is caused by how much work is being done by the browser and/or how what the CPU load is and that explains why @terracoda say it intermittently. Ultimately, I think there is a risk that this will happen in the wild for those that are using older macOS devices with Firefox, so it would be good to discuss the implications of this with others on the team.

In comments in this issue I documented attempts to fix the crashing but didn't find any sort of workaround. @emily-phet @terracoda @BLFiedler can we discuss how to proceed?
- We could accept this as a reasonable risk considering macOS + Firefox is rarely used in classrooms. In fact, it is not listed officially as one of PhET's supported platforms.
- We could submit a bug report to Mozilla about this.
- We could disable all Voicing on Firefox on macOS devices.
- I could continue searching for a workaround, but I am not sure what else we can do.

**Comment by terracoda** [comment]
Just to be sure, I also just tested on a new MacBook Air (M1, 2020)
- MacOs Big Sur version 11.3
- Chip Apple M1
- Memory 16 GB

Firefox version 88.0.1 (64-bit)

No crashing. No issues.

**Comment by terracoda** [comment]
@jessegreenberg, I think it is worth a bug report to Mozilla, for sure. We have some quite specific data re OS versions, CPUs and FF version that could be helpful. In my case, the crashing was very consistent on the version 77 and there was no crashing on the other versions.

I don't think we should disable Voicing on Firefox on MacOs. That seems too drastic to me.

**Comment by jessegreenberg** [comment]
Over Slack, @terracoda agreed to try a test on her Firefox machine to see if we can get it to crash like my mac even with the latest Firefox.

Here is a link to the version: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.14/phet/john-travoltage_en_phet.html

It has a function on the window that can be called from `window.startTest()` from the console, which will spam the Toolbar open button with presses.

**Comment by terracoda** [comment]
@jessegreenberg showed me how to window.StartTest() on my old mac (https://github.com/phetsims/john-travoltage/issues/422#issuecomment-850639220). The Toolbar was opened and closed 3300 times without a crash.

Version tested: john-travoltage/1.6.0-preferences.14

I will test on iPad and iMac, too, as asoon as possible and report back here.

**Comment by terracoda** [comment]
Testing today on 
iMac Retina 4k, 21.5-inch, 2019
MacOS 10.15.7
Processor 3 GHz- 6-Core Intel Core i5
Mem 16GB 2667 MHz DDR4
Graphics Radeon Pro 560x 5GB

iPad
more details to come

**Comment by terracoda** [comment]
@jessegreenberg, I have exhausted my mac devices. 

As I said in https://github.com/phetsims/john-travoltage/issues/422#issuecomment-850728600 , a bug report may be the way to go.

I feel confident we don't have to restrict Voicing to certain browsers or platforms.

From my point of a view an update from version 77 to 78 solved the crashing problem on my old Mac and I didn't experience any issues on other systems I tested on.

I unassigned myself. Let me know if there is anything else needed fro this issue.

**Comment by terracoda** [comment]
We discussed this issue and how to proceed in the Voicing meeting today. We all felt that the crashing issue seems rare enough that we can proceed with a bug report and no browser or device restrictions for the Voicing feature when we are ready to publish our first sim with Voicing.

I am going to mark this issue as won't fix, and make a new issue to create the bug report.
I hope that is a reasonable path forward.

**Comment by terracoda** [comment]
Maybe we don't need a new issue for the bug report? 
@jessegreenberg, can you close this issue when you have created a bug report to Firefox about speechSynthesis crashing the browser.

Or let me know how to create a bug report :-)
Thanks for all your hard work on this issue.

**Comment by jessegreenberg** [comment]
Sounds good @terracoda, thanks! I just submitted a bug report for this with the details from my crash on the device where it happened. Closing this issue then.
