### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/john-travoltage#426]
While reviewing the [updated sim pages](https://ox-dev.colorado.edu/en/simulations/john-travoltage) on ox-dev, I noticed that the alternate screenshot is identical to the main screenshot. The screenshots currently checked in are indeed identical, but the alt used to look like this:

![image](https://user-images.githubusercontent.com/8419308/124668175-b5554d00-de6d-11eb-8369-60a8e6a99023.png)

**Comment by arouinfar** [comment]
I ended up updating both screenshots using the latest dev version on the preferences branch so the navbar icons would all be present.

There's no urgent need to update the sim screenshots on the website, so this change can wait until the next redeploy from master.

I don't think there's anything to cherry-pick here since there'll probably be a new release branch created when the sim redeploys, but assigning @jessegreenberg to confirm.

**Comment by jessegreenberg** [comment]
> I don't think there's anything to cherry-pick here since there'll probably be a new release branch created when the sim redeploys, but assigning @jessegreenberg to confirm.

Yes, we will be republishing this sim again off of master. -Would you like to keep this open or OK to close?

**Comment by arouinfar** [comment]
Let's close @jessegreenberg
