### ISSUE TITLE
Keyboard Shortcuts dialog - updates for new Move Hand direction

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#428]
In issue #425 we reversed the direction of the Arm Swing interaction to better align with swipes when using iOS VoiceOver and to be the same direction as the Leg Swing interaction.

We felt this change required changes to how we describe these interactions in the Keyboard Shortcuts dialog. We decided to explicitly describe the preferred directions using the Arrow keys, though all directions work just fine because these are slider interactions. All four arrow keys work by default to augment and decrement sliders.

The Interactive Description Design Document has been updated with the following information.
![Screen Shot 2021-07-13 at 4 16 57 PM](https://user-images.githubusercontent.com/1902116/125510600-15a749f0-6287-42d7-b2c3-7af604a83a35.png)

In the Accessible Content these interactions are as follows:
H2: Hand or Foot
UL:
  LI: Move foot with Left and Right Arrow keys.
  LI: Move hand with Up and Down Arrow keys.

The heading, Tab to get started, and Basic Actions are all part of common code.

**Comment by jessegreenberg** [comment]
Updates made, @terracoda can you please review in this version?

https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-dev.44/phet/john-travoltage_en_phet.html

**Comment by terracoda** [comment]
Looks and sounds awesome! Thanks.
