### ISSUE TITLE
(PDOM Preferences Menu)Audio Features - I hear context response twice

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#429]
In general, the pdom access with a screen reader to the Preferences Menu is sounding really good. 

One issue I found is when I toggle the on/off switch for the Audio Features, I hear the context responses twice. It doesn't seem to happen on the other on/off switches.

This is when using a screen reader not voicing.

I am using Safari and VoiceOver on MacOs Big Sur 11.4
MacBook Pro Apple M1 chip

**Comment by jessegreenberg** [comment]
Confirmed in the a11y view: 
![image](https://user-images.githubusercontent.com/6396244/126391362-232f59f1-6b07-4dd5-a9d6-5e2e14486d4b.png)

**Comment by jessegreenberg** [comment]
Fixed in the above commit.
