### ISSUE TITLE
Text covers toggle button in preferences during stringTest=long

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/john-travoltage#431]
**Test device**
MacBook Air (M1 chip)

**Operating System**
11.4

**Browser**
Chrome 91.0.4472.114 

**Problem description**
https://github.com/phetsims/qa/issues/676 

In stringTest=long, the text covers the toggle button in the visual preference section (where it normally says interactive highlights). I see the same problem in audio preferences as well. 

**Steps to reproduce**
1. add ?stringTest=long to the end of the URL.
2. click on the preferences icon
3. click on the second set of numbers (where "visual" normally is)

**Visuals**
<img width="1029" alt="Screen Shot 2021-07-26 at 1 30 30 PM" src="https://user-images.githubusercontent.com/87318828/127034564-8e8896f7-49d3-4947-90f3-c1a4ce3a5f93.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-rc.1/phet/john-travoltage_all_phet.html?
Version: 1.6.0-rc.1 2021-07-22 18:05:38 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1157x687
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
Also seen in stringTest=rtl

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi -

Looks like it is because of the description for the toggle switch, when there is no description the layout is OK:
![image](https://user-images.githubusercontent.com/6396244/127040955-99b132b9-754f-4af2-b0d3-6e746cb110ce.png)

Caused by these lines:
```js
      // if there is a description Node, label is left aligned with it
      if ( options.descriptionNode ) {
        options.labelNode.leftBottom = options.descriptionNode.leftTop.minusXY( 0, options.descriptionSpacing );
      }
      else {
        options.labelNode.rightCenter = toggleSwitch.leftCenter.minusXY( options.labelSpacing, 0 );
      }
```

**Comment by jessegreenberg** [comment]
This should be improved in the above commit. @Nancy-Salpepi would you mind checking master and verifying this is fixed? If so, I will merge this commit into release branch.

**Comment by Nancy-Salpepi** [comment]
Still having the same issue @jessegreenberg

**Comment by jessegreenberg** [comment]
Sorry, I should have clarified this fix was in joist and I see that joist is still out of date on bayes:
![image](https://user-images.githubusercontent.com/6396244/127061075-bf3836f2-bd6b-4b79-b1f0-50d26ffd0e47.png)

Could you please pull joist and try again?

**Comment by Nancy-Salpepi** [comment]
The issue is fixed in master

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, fix applied to john-travoltage-1.6 branch of joist and joist SHA updated in 1.6 branch of the sim.

**Comment by KatieWoe** [comment]
On ChromeOS this also occurs with rtl

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe that should also be fixed after https://github.com/phetsims/joist/commit/a515f134125688ab3885f0d3951517c0c52acd1a
