### ISSUE TITLE
Exposed HTML tag in the Credits

### ISSUE THREAD

**Issue by phet-steele** [phetsims/john-travoltage#432]
There is a < br > just before Taliesin's name.

![image](https://user-images.githubusercontent.com/5863899/127067683-dd286218-bc42-4011-b349-86c4e2f145bc.png)

Seen on Win 10 Chrome. For phetsims/qa/issues/676.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-rc.1/phet/john-travoltage_all_phet.html
Version: 1.6.0-rc.1 2021-07-22 18:05:38 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1920x937
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by jessegreenberg** [comment]
Oh thanks! Fixed in the above commit and joist SHA updated in the 1.6 branch.
