### ISSUE TITLE
"Samantha" listed twice in the combo box

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/john-travoltage#436]
**Test device**
MacBook Air M1chip

**Operating System**
11.4
**Browser**
Safari 14.1.1

**Problem description**
https://github.com/phetsims/qa/issues/676

In audio preferences, the name "Samantha" appears twice in the combo box. 

**Steps to reproduce**

1. Click on the preferences icon in the toolbar panel
2. Navigate to audio preferences
3. Enable voicing by moving the toggle button
4. Expand the customize voice panel

**Visuals**
<img width="1004" alt="Screen Shot 2021-07-27 at 1 55 49 PM" src="https://user-images.githubusercontent.com/87318828/127206060-7d58d531-e208-4ff9-854a-6d30c8d7b6ad.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-rc.1/phet/john-travoltage_all_phet.html
Version: 1.6.0-rc.1 2021-07-22 18:05:38 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Language: en-us
Window: 1352x683
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi. Safari on my macOS 11.4 only has Samantha listed once. The voices in the ComboBox are provided by the browser/operating system. Can you please comment on whether the two "Samantha's" sound different? If they really are a duplicate, we probably want to prune the list. If they sound different, maybe we want to rename the second one? Im not sure.

**Comment by Nancy-Salpepi** [comment]
The first Samantha option does not work. The name isn't said aloud when I choose it and no voicing occurs with it.

**Comment by jessegreenberg** [comment]
Oh wow - ok understood. Ideally the broken one would be removed. But I don't know how we can distinguish the broken one from the working one.

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi mentioned the duplication was only in Safari.

**Comment by Nancy-Salpepi** [comment]
To be more specific--it wasn't on chrome. I have only looked at those 2 browsers so far.

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi can you please test this now? I made it so that any voices of the same name will be removed from the list. Hopefully removing the duplicate will make it so the one that remains works.

The fix was in joist, so to test go to phettest and pull joist, then run john-travoltage again from master.

**Comment by Nancy-Salpepi** [comment]
There is only one Samantha now listed, but that one doesn't work.

**Comment by jessegreenberg** [comment]
I am not sure if there is anythign we can do about this. But I think it would be helpful to meet briefly and inspect the voices on @Nancy-Salpepi's machine to see if the broken "Samantha" has anything about it that would let us prune it from the list. We scheduled a time tomorrow to take a look.

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi and I took a look this morning and noticed that the "Samantha" voices had the same name but a different `voiceURI` property. 

<img width="1044" alt="Screen Shot 2021-07-28 at 9 10 15 AM" src="https://user-images.githubusercontent.com/6396244/127350873-e505b1e3-29a4-4801-99a1-393574fae3c3.png">

The "broken" voice had "premium" as part of the URI. I am going to try to remove voices with that in the URI for now. I don't really like this fix because I don't have confidence that it will be broken for all platforms. 

@Nancy-Salpepi can you please verify that this was fixed in master by pulling joist and testing on phettest?

**Comment by Nancy-Salpepi** [comment]
Now in the combo box, Samantha is the ONLY voice listed 
<img width="960" alt="Screen Shot 2021-07-28 at 11 44 20 AM" src="https://user-images.githubusercontent.com/87318828/127354096-a417450d-c029-4f69-a069-48aaa239fb3e.png">

**Comment by jessegreenberg** [comment]
I see, thanks @Nancy-Salpepi - so that confirms the case that we cannot remove all "premium" voices. Many (most) with "premium" in the URI work fine.

I would like to discuss this with @emily-phet and @terracoda.

**Comment by jessegreenberg** [comment]
Discussed with @emily-phet and @terracoda:

This problem is outside of PhET's control and we will not spend more time trying to find a workaround. We will do a quick check to see if we can find a fix on the machine where this happened, but otherwise we will let this go.

**Comment by KatieWoe** [comment]
On iPadOS 14.7.1, Samantha seems to be the only available option. Should the combo box still be in place with a case like this?

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/joist/commit/0ec5b29dfca412d79ccee73605aea58736d63010 and https://github.com/phetsims/joist/commit/b18a3085fa5fdc3d782156455e1a3efb9fd875f0 need to be reverted in master.

Regarding https://github.com/phetsims/john-travoltage/issues/436#issuecomment-890080426

Good question @KatieWoe. I suspect this is OK, but its a good design question. @terracoda @emily-phet would you like to change the UI when there is only one voice available?

**Comment by emily-phet** [comment]
I think it's fine to leave this as-is - combobox interface even if only 1 voice in place. All of our general supporting materials for voicing and preferences menu will indicate that this is a combobox, and will also make clear that the list is the list of voices available on your current device. I think with that support, many people will recognize they only have one option because their device has only one option to populate it with.

**Comment by jessegreenberg** [comment]
OK, thanks @emily-phet, closing.

**Comment by jessegreenberg** [comment]
These changes have been reverted in the above comits.

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg I started to do the spot check on safari and there is only 1 Samantha voice listed now, but that one does not work.

**Comment by KatieWoe** [comment]
Linking to https://github.com/phetsims/qa/issues/697

**Comment by terracoda** [comment]
I am un-assigning myself from this issue.

**Comment by jessegreenberg** [comment]
Unfortunately there is nothing we can do on the sim side to fix this voice or remove this voice. In https://github.com/phetsims/john-travoltage/issues/436#issuecomment-889409141 we agreed to continue publishing with this issue.

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi and I just paired on the machine where this is broken. We found that by going to system voices and deleting "Samantha" then re-downloading "Samantha" fixed this problem for her machine. Unfortunate that we cannot fix this in the sim, but this gives us something to recommend if we get reports of this in the wild.

**Comment by jessegreenberg** [comment]
Closing this again.
