### ISSUE TITLE
Voicing incorrect when navigating in PhET menu

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/john-travoltage#437]
**Test device**
MacBook Air M1 chip

**Operating System**
11.4

**Browser**
Safari 14.1.1

**Problem description**
https://github.com/phetsims/qa/issues/676

The voicing descriptions don't match the items in the PhET menu. When the PhET menu is clicked open, voicing says "PhET website." When Screenshot or Full screen is selected, voicing says "PhET menu." When About or Check for Updates is selected, voicing says "close."

**Steps to reproduce**
1. Open preferences and navigate to audio tab
2. Turn on voicing
3. Click on the PhET logo to open menu
4. select any of the following options: Screenshot, Full Screen, About or Check for Updates

**Visuals**

https://drive.google.com/file/d/1FcZwC9kyG9-p37P-Nhl5Y2Xs5jybAwXC/view?usp=sharing 

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-rc.1/phet/john-travoltage_all_phet.html
Version: 1.6.0-rc.1 2021-07-22 18:05:38 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Language: en-us
Window: 1352x683
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, good point.

This is happening for two reasons.
1) We don't have voicing responses describing activation of components in the menu.
2) Even if we did, focus is moving to something else in the menu and so the newly focused element triggers a voicing response. For example, in the steps mentioned above
- Open preferences and navigate to audio tab
- Turn on voicing
- Click on the PhET logo to open menu
-   **Focus just moved to the first menu item, so it says "PhET Website".
- select any of the following options: Screenshot, Full Screen, About or Check for Updates
  - **Focus either moved back to the menu button or to the "Close" button in the dialog. **

Would like to discuss with @terracoda about what to do about this and if a fix should be made for this publication.

**Comment by jessegreenberg** [comment]
Discussed with @terracoda and @emily-phet.

Consensus: We will proceed with publication of JT and the upcoming sims with this problem for now, but revisit this potentially next quarter.

@jessegreenberg to follow up on this issue with other things that were discussed during the meeting.

**Comment by terracoda** [comment]
Just to help @jessegreenberg, with comments and meeting note, we discussed ideas around:
- renaming the PhET Menu button to either Open PhET Menu or PhET Menu Closed. We didn't like these ideas, and felt they would not beneficial in the short term
- review the behaviour of the PhET Menu, e.g., does the menu need to auto close after the action-oriented items? This needs to be discussed more generally with the team and may provide a roust long term solution.

**Comment by jessegreenberg** [comment]
Thanks @terracoda - that is correct. Since we decided to defer this I am going to close this issue. When we decide to improve the behavior with Voicing of the PhET menu, we can open a new issue in joist.
