### ISSUE TITLE
Voicing default details unhelpful

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#439]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/676. When turning on voicing during our last look at this sim, object details/changes and context changes were on by default. In this rc, all seem off by default. This means that very little is read out by default, such as that the arm and leg are swinging. Nothing about the number of electrons, or discharging.

**Visuals**
Old default:
<img width="288" alt="before" src="https://user-images.githubusercontent.com/41024075/127691363-c428bd8d-e015-41b2-933f-aeb82a06c4da.png">
New default:
<img width="266" alt="now" src="https://user-images.githubusercontent.com/41024075/127691391-34a64f92-53f3-4d97-a0ea-5b9cc92dec22.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-rc.1/phet/john-travoltage_all_phet.html
Version: 1.6.0-rc.1 2021-07-22 18:05:38 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
Language: en-US
Window: 1280x675
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - Correct, it was decided for now that the default behavior for voicing should be more terse, so that the feature is not overwhelming to people that initially find it.

But it is useful to know this was your interpretation of the change, and would be good for @terracoda or @emily-phet to review and confirm this is OK and correct before closing.

**Comment by emily-phet** [comment]
@jessegreenberg Yes - this is the intended default behavior for version, none of the Voicing checkboxes checkboxes.

@KatieWoe - With Voicing enabled, but no checkboxes checked, you should still be able to hear object names as you click/tap/navigate to different objects, and you should be able to hear the reading blocks (in sims that have them, John Travoltage has no reading blocks, but GFLB does). If that's your experience, then the behavior is as expected.

**Comment by terracoda** [comment]
@KatieWoe, and of course you have access to the reading button in the toolbar as well :-)
