### ISSUE TITLE
sluggish on Win7+Firefox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#44]
This is Win7 running on VMware.

Troubleshooting information
Name: John Travoltage
URL: http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.0.0-rc.1/john-travoltage_en.html
Version: 1.0.0-rc.1
Features missing: flexbox, touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0
Language: en-US
Window: 1066x671
Pixel Ratio: 1/1

**Comment by phet-steele** [comment]
The sim is definitely fine on Win7 FF 52. @pixelzoom do you even have a Win 7 platform you would like to check performance on? Otherwise, fine by me to close.

**Comment by pixelzoom** [comment]
Since this is so ancient, and no one else sees the problem... Closing.
