### ISSUE TITLE
Many hard coded strings

### ISSUE THREAD

**Issue by zepumph** [phetsims/john-travoltage#444]
I found that there are some hard coded string in `JohnTravoltageView.js` while working on https://github.com/phetsims/utterance-queue/issues/13. For example https://github.com/phetsims/john-travoltage/blob/69df7131ce4415879f71aedb76ef2b77b585e20e/js/john-travoltage/view/JohnTravoltageView.js#L406, shouldn't these be in the strings file?

**Comment by jessegreenberg** [comment]
Thanks @zepumph, strings either removed or moved to strings file.
