### ISSUE TITLE
CT tried to removeListener on something that wasn't a listener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#445]
```
john-travoltage : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1628759848901%22%2C%22timestamp%22%3A1628763588058%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/assert/js/assert.js:25:13)
at Timer.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/axon/js/TinyEmitter.js:135:7)
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/axon/js/Timer.js:33:16)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/joist/js/Sim.js:303:17
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/axon/js/Action.js:227:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/joist/js/Sim.js:1083:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/joist/js/Sim.js:1073:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1628759848901/joist/js/Sim.js:1051:12)
id: Bayes Chrome
Snapshot from 8/12/2021, 3:17:28 AM
```

**Comment by jessegreenberg** [comment]
This seems pretty rare, and I am not sure what is causing it yet. Fuzzing on my local machine with the same query parameters isn't showing it, and it isn't in the last 10 CT collumns.

But I have seen this once before as well on CT before the snapshot @KatieWoe posted so I don't think it is gone.

**Comment by jessegreenberg** [comment]
The case that we are running into is this in Timer.setTimeout

```js
        // make sure that this callback hasn't already been removed by another listener while emit() is in progress
        if ( this.hasListener( callback ) ) {
          listener();
          this.removeListener( callback );
        }
```

The listener must be removing itself so `this.removeListener` errors out.

**Comment by jessegreenberg** [comment]
I am seeing this in GFL:B as well in the last 10 CT cycles, must not be specific to this sim. Going to try to get it to happen there.

**Comment by jessegreenberg** [comment]
Found more information about why this is happening:
![image](https://user-images.githubusercontent.com/6396244/129458261-ebf9c493-7822-496a-b239-5ea119f82be8.png)

When a speech request is made, something is causing the queue to synchronously clear (and therefore remove timer listeners) from within the setTimeout listener.

**Comment by jessegreenberg** [comment]
I found it. What is happening is:
- voicingManager starts speaking from within the timeout
- For some reason, the SpeechSynthesis `error` event triggers. `voicingManager.endSpeakingEmitter` fires from that event.
- A listener on that Emitter sets another Property in VoicingToolbarItem that has yet another listener that eventually calls voicingManager.cancel().
- All listeners on the timer are remove in cancel, including the one that is currently firing. Then Timer.js tries to remove the timer that was already removed, causing the assertion.

`endSpeakingEmitter` being called on the error event seems correct to me, and I don't think there is anything wrong about the client usage. I think we need to be more graceful in voicingManager by not removing the listener in cancel() if cancel was initiated immediately from a request to speak.

**Comment by jessegreenberg** [comment]
This was fixed in the above commit. I was able to step through the problematic case and verify that the listener was not removed twice, but was successfully removed once at the end of the callback. Closing.
