### ISSUE TITLE
Update QA credits

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/john-travoltage#446]
https://github.com/phetsims/qa/issues/693

I noticed that the credits need to be updated. I am in the process of finding out what QA members worked on the sim.

**Comment by jessegreenberg** [comment]
Thanks for reporting @Nancy-Salpepi, reassigning to you please reassign to me once the updated list is ready.

**Comment by Nancy-Salpepi** [comment]
The additional QA members are:
Logan Bray, Clifford Hardin, Liam Mulhall, Devon Quispe and Nancy Salpepi

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, updated and cherry-picked into the RC branch in the above commits.

**Comment by KatieWoe** [comment]
Credits are unchanged for rc.3

**Comment by jessegreenberg** [comment]
Thanks, nothing more for this release then, closing.
