### ISSUE TITLE
Mobile VO skips over part of scene description sometimes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#449]
**Device**
iPad 6th Gen
**OS**
iPadOS 14
**Browser**
Safari
**Problem Description**
Occurs in published sim. When listening to the scene description line by line, sometimes the line reading the number of electrons is omitted. This seems to happen after swinging the leg. I also didn't seem to be hearing alerts during discharge or reading new number of electrons. The scene description line was returned if I swiped two fingers up and listened to the description that way.
Sorry for missing this. Not sure how it got through.
**Visuals**

https://user-images.githubusercontent.com/41024075/130273286-03ded3df-7a2a-469e-ac7a-772c071ec2fb.MOV

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - never seen this before and not sure what would cause it. I don't have an iPad at the moment but for when I can look at this next:
- The bug starts around the 30s mark.
- The second paragraph of the screen summary is being skipped.

> John has 5 charges on his body. John has hand close to doorknob, and he is ready to swing his leg to rub his foot on the rug.

It is as though the virtual cursor stays on the second paragraph. Swiping left reads the first paragraph and swiping right reads the third one.

**Comment by KatieWoe** [comment]
As mentioned, I also wasn't seeing alerts.

**Comment by jessegreenberg** [comment]
Was able to reproduce on my iPad, seems to happen whenever there are charges on the body. Not sure why yet.

**Comment by jessegreenberg** [comment]
I am going to try to reproduce this in a basic HTML page.

**Comment by jessegreenberg** [comment]
We were able to investigate this in depth in https://github.com/phetsims/a11y-research/issues/175. Unfortunately it is an Apple bug and we are not going to search for a workaround. See that issue for more details, closing.
