### ISSUE TITLE
PDOM focus highlights are now Rectangles?

### ISSUE THREAD

**Issue by zepumph** [phetsims/john-travoltage#465]
@terracoda and I were surprised to see that the foot and leg focus highlights are now rectangles instead of circles. We weren't sure if this was purposeful.

![image](https://github.com/phetsims/john-travoltage/assets/6856943/69b2dd1c-ec40-4d86-aeee-bd90e047dfe9)

It was also weird that the rectangle changes size, pointing to this being a bug. @jessegreenberg do you know if this is a regression or purposeful?

**Comment by jessegreenberg** [comment]
Good catch! It looks like this may have happened from c2447f7449e610e42d3b9bf2b72a010f0351d713 for https://github.com/phetsims/phet-io/issues/1947. Fixed, closing.
