### ISSUE TITLE
Some charges can move in between the body and arm across the air

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#57]
@orejolaphet said: Although I did notice that now some charges can move in between the body and arm across the air. I'm not sure if its from the polygon fix or if it was intentional, but I thought it was appropriate to let you know. 
![118a5f50-4580-11e3-8eed-caf51eed2964](https://f.cloud.github.com/assets/679486/1467343/a4ea7898-4580-11e3-97f8-7908dcc25263.png)

**Comment by ariel-phet** [comment]
Completely stale, closing
