### ISSUE TITLE
Should you be able to create a spark without moving the hand?

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#68]
In the original Java version, you can create a spark without moving a hand. In HTML5 version 1.0 you had to move the hand, even if full of charges.  In HTML5 1.1 you can create a spark without moving the hand.  What is better for students?  Perhaps it would be good to discuss with Emily since she has interviewed on this sim.

**Comment by ariel-phet** [comment]
After reading over this issue, playing with sim, and considering tweaks, I think it is best to leave as is currently:

- the current behavior and model took some tweaking and seems to cover the learning goals well
- although dieletric breakdown does not usually occur so far in regular life, I think we can assume that the character of John Travoltage acts a bit more like a vandagraff and is able to pick up more charge than the normal human
- the concern of having students move the hand is not bothering me anymore. If you only rub the foot, even if John discharges, a green box remains around the hand/arm suggesting it is moveable

Closing, as it seems the sim in its current form works fine as is.
