### ISSUE TITLE
No audio in Firefox 31.0 on Win8

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#75]
http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.2.0-dev.1/john-travoltage_en.html

No audio in Firefox 31.0 on Win8.

Is this a new problem?

**Comment by phet-steele** [comment]
@samreid, the vibe issue is closed and we certainly have audio on Win 8.1 FF these days. Can this be closed?

**Comment by samreid** [comment]
Since vibe is closed and the sim passed QA, this issue can be closed.
