### ISSUE TITLE
branch: canvasnode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#78]
Please describe or delete if no longer necessary.

**Comment by samreid** [comment]
Should be revisited before republication.

**Comment by pixelzoom** [comment]
Marked as "Summer 2015 redeploy" since @samreid said "should be revisited before republication". @samreid do you know what this branch is for, what it was exploring, etc?

**Comment by samreid** [comment]
Performance is poor on iPad.  I'm thinking using scenery's WebGL support for images will solve most of this issue.  I deleted this branch.
