### ISSUE TITLE
Remove or document renderer overrides

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#80]
See https://github.com/phetsims/joist/issues/225

**Comment by jessegreenberg** [comment]
The renderer is overridden with 

```js
    //The sim works best in most browsers using svg. But in firefox on Win8 it is very slow and buggy, so use canvas on firefox.
    ScreenView.call( this, {
      renderer: platform.firefox ? 'canvas' : 'svg',
      layoutBounds: new Bounds2( 0, 0, 768, 504 )
    } );
```
In phetsims/joist#225 @samreid said
> so it will need Win8/FF tests to see if we can drop this yet.

I just tested this sim without the renderer override on a Windows 8 Machine with Firefox 44 (PhET test machine Socrates).  Indeed, the animation of charges was much slower with the SVG renderer.

It seems like we still need this line, and the documentation looks good to me. @samreid anything else to investigate here or can we close?

**Comment by samreid** [comment]
This seems good for now, thanks for investigating @jessegreenberg, closing.
