### ISSUE TITLE
branch: accessible-instance

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#90]
Branch created to prototype accessible content including keyboard navigation and screen readers.  See #89.

**Comment by pixelzoom** [comment]
@jessegreenberg I don't see this branch, was it deleted? If so, please close this issue.

**Comment by jessegreenberg** [comment]
Yes it was, thanks @pixelzoom.

**Comment by jessegreenberg** [comment]
Re-deleted for https://github.com/phetsims/special-ops/issues/198
