### ISSUE TITLE
Total charge level sonification feedback

### ISSUE THREAD

**Issue by jhung** [phetsims/john-travoltage#91]
@jbphet, I took at look at the latest on sonification.

The sonification associated with total charge level could be ambiguous because it occurs the same time charges are gained.

Instead, I think the total charge level could be a constant, subtle background noise that increases in volume as charges increase. Similar to how a computer / laptop fan is audible when idle, and gets a little louder (but not distracting) as the temperature of the CPU increases.

Thoughts?

**Comment by jbphet** [comment]
@jhung - I haven't added a sound for total charge level yet, so I'm not sure what you're referring to.  Are you describing what has been proposed?

**Comment by emily-phet** [comment]
This issue is out of date - sonification has progressed significantly since the start of this issue.
