### ISSUE TITLE
add sonification

### ISSUE THREAD

**Issue by jbphet** [phetsims/john-travoltage#92]
We have decided to add sonification to this sim.  A number of commits have already been made for this, I'll list them in the next comment.

The spec can be found here: https://wiki.fluidproject.org/display/fluid/PhET+John+Travoltage+Sonification+Design

**Comment by jbphet** [comment]
Below are the commits that were made as part of the effort to add sonification prior to the creation of this GitHub issue:

6149d8b5eecc4165a5ad6e3b9dd930ad1e408409
fcacd848f84e5171399a2a9248ef26b7ea3824f1
fc2267d270b6c1ee1f9f6afd3aec8411c97cdd73
76eec2fd1852e2c36ba227c7480e3d2df69f174d
a7e4d1689de2550e7b64fe8765c208a3c2e56b3c
36459746ed7c59133641c451ec1b10a9289a19a0
017a0dc0fc874449cc1ebbfd1ab0f60bb0b11130
d552b091c82769942eeab4c7b6f7f8d93674223a

**Comment by jobara** [comment]
@jbphet i was trying this out in Safari today. I keep getting this error "SyntaxError: audio resources unavailable for AudioContext construction" from ToneGenerator.js line 38, during load of the sim.

**Comment by jbphet** [comment]
@jobara - This has only been tested in Chrome so far.  We can discuss during today's meeting if we need to focus on wider browser support.

**Comment by samreid** [comment]
@jbphet it looks like there are 6 files related to audio (of the 14 files in the view).  Can they be moved to a separate folder?

**Comment by samreid** [comment]
I've moved them to an audio/ folder.

I also asked @emily-phet:
> We need to know whether the sonification prototypes John Blanco built a few months ago are an essential part of the ETS PhET-iO instrumentation, or if they are not needed for that deadline.

**Comment by jbphet** [comment]
Notes from 4/18/2017 discussion with @emily-phet:

+ Add a sound for reset - this is a potentially reusable sound for all sims, and it is the only sonification the user should hear when they press the reset button, and all the other sounds that may result from a reset of the model are suppressed.
+ The carpet rubbing sounds (both forward and backward) should be a bit gentler.  Maybe try running through a filter, re-record if necessary.
+ Sound for particles going in is good, leave as is (at least for now).
+ For the charge level, which plays continuously based on the amount of charges present in the body, we should try a wind chime sort of sound somewhat like the one found here: https://www.youtube.com/watch?v=pY2VThYORq0.  As the level of charge increases, the volume should increase.  We may try making the tickles happen more or less often.
+ For the arm motion, the current sounds are a little heavy, and we'd like to try moving somewhat towards a slide whistle sound, but without making it sound too much like a cartoon.

**Comment by jbphet** [comment]
The sim was published a while back with sonification available behind a query parameter.  We've done a lot of sound design work since then, and the sonification in this version will be completely redone in the next few months.  I think the best thing is to close this issue, and do the new sonification work under a new GitHub issue when the time comes.
