### ISSUE TITLE
Determine method of referencing node's PDOM element

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#99]
In AccessibleDescriptionNode, there is the following line:

```
//TODO: Is there a better way to set the 'aria-describedby' relationship? This doesn't seem very robust.
describedNode.getAccessibleInstances()[0].peer.domElement.setAttribute( 'aria-describedby', domElement.id );
```

Agreed!  At the moment, there is no good way to reference a node's representative element in the PDOM.  In scenery, we should create an issue to address this (and other such issues like this).  Once it is addressed, we should update his solution.

**Comment by jessegreenberg** [comment]
A short term workaround could be to add the dom element id to describedNode as a public variable so that the relationship could be defined by
```js
document.getElementById( describedNode.accessibleId ).setAttribute( 'aria-describedby', domElement.id )
```

**Comment by jobara** [comment]
@jessegreenberg i refactored to use your suggestion. I think a useful improvement could be to make the accessible peer available off of a node automatically.

**Comment by jessegreenberg** [comment]
@jobara rather than the AccessiblePeer what do you think about making the parallel dom element available from a node?

Then the line in https://github.com/phetsims/john-travoltage/issues/99#issue-161302584 would then look something like
```js
describedNode.domElement.setAttribute( 'aria-describedby', domElement.id );
```

**Comment by jobara** [comment]
@jessegreenberg yes, this is actually what I meant, but my terminology was poor. Thanks for sorting it out. Also what do you think about renaming domElement to pdom or parallelDOM, both here and internally when creating the markup? It might be more explicit about what it is for, assuming one knows what a parallel DOM is.

**Comment by jobara** [comment]
@jessegreenberg I made another change to my [jt-a11y-89 branch](https://github.com/jobara/john-travoltage/tree/jt-a11y-89) to include the restructuring you outlined above. In the future it would be good if the framework (scenery?) could just add the domElement to the node automatically.

**Comment by jessegreenberg** [comment]
Thanks @jobara, I opened https://github.com/phetsims/scenery/issues/553 to track adding this to Scenery.  In terms of naming, what do you think about ```accesssibleDOMElement```?

**Comment by jessegreenberg** [comment]
This was handled as part of #132, for a Node with accessible content, the domElement can be accessed through a getter. Closing.
